### ISSUE TITLE
fruitMass

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#10]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | fruiMass |
| **Definition** | The mass in grams of a fruit of a flower exposed to a single visitor. |
| **Comments** |  |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Definitions:

`The mass in grams of a fruit of a flower exposed to a single visitor`
and
`Percentage of flowers exposed to floral visitors during anthesis that set fruit`

@pzermolgio:
>this is probably something you can't measure. You may have recorded one, or more, interactions, but you would need to track the plant over it's flower lifespan to determine this...

> exposed is not clear. Exposed does not imply that visitors actually visited.

**Comment by fonturbel** [comment]
I am not sure why are you setting the single visit condition in here, why not just the average mass? it would give you an idea of the average mass of one fruit

**Comment by lgcarvalheiro** [comment]
This might be a bit too specific for many poeple to contribute, but I am guessing this was included so that there is possibility to had information on the effect of pollinators on quality.  However, as there are multiple measures of fruit quality (weight, sugar content, shape, etc) I wonder if it would not be better to have a more general term such as "fruit quality" where people could add different types of measures of fruit quality (and in another column, provide information on the units of fruit quality)

**Comment by zedomel** [comment]
@lgcarvalheiro If we adopt what you are suggesting, Darwin Core already has a class [`MeasurementOrFact`](http://rs.tdwg.org/dwc/terms/MeasurementOrFact) that can be used here.

The class define a set of terms, including:
- [measurementType](http://rs.tdwg.org/dwc/terms/measurementType):  `The nature of the measurement, fact, characteristic, or assertion.`. Examples: `tail length`, `temperature`, `fruit weight`, `fruit sugar content`
- [measurementValue](http://rs.tdwg.org/dwc/terms/measurementValue):  `The value of the measurement, fact, characteristic, or assertion`. Examples: `45`, `20`, `1.5`
- [measurementUnit](http://rs.tdwg.org/dwc/terms/measurementUnit): `The units associated with the measurementValue.`. Examples:  `cm`, `kg`, `ml` 
- [measurementMethod](http://rs.tdwg.org/dwc/terms/measurementMethod): `A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion`. Examples:  `minimum convex polygon around burrow entrances`.

The problem using that solution, is that the `measurementType` values are not standardized (it is a free text term), so people can fill the term with any expression. It will make difficult, if not impossible, to aggregate data later. On other hand, we can provide a controlled vocabulary for `measurementType` which includes `fruit weight`, `fruit sugar content`, etc. Actually, this is the way we are building the data standard for many terms: **creating a controlled vocabulary to be used with `dwc:MeasurementOrFact`**. 

So, the terms like `fruitSet`, `floralReward`, `sexualSystem` and many others can be use as values to the `measurementType` having the corresponding `measurementValue` (e.g. `nectar`, `monoecious`). 

In the end, we have to provide definitions to terms like `fruitMass`, `fruitShape`, `fruitSugarContent` etc. 

@fonturbel  the **single visit condition` here is something tied to the protocol, and we should avoid to define a term that implies adoption of a protocol in its definition. So in my opinion a better definition should be:  `The mass in grams of a fruit of a flower`. But there are other problems with that definition too:

- Which flower? The  flower which the `Interaction` was recorded`? And what about if we did not record the `Interaction`, just let the flower exposed and then measure the fruit mass to compare to the fruit mass of bagged flowers?
- If we do not make explicit that the flower is the flower where the Interaction actually occurs, and have a one-to-one relationship with an Interaction (one Interaction - one Fruit Mass), then the fruit mass can be related to many **interactions** (e.g. average fruit mass), so how can we know which **interactions** were responsible to this results?

**Comment by zedomel** [comment]
**New definition**: `The mass in grams of a fruit of a flower exposed to a single floral visitor`

**Comment by zedomel** [comment]
**New definition**: `The mass in grams of a fruit of a flower exposed to a single floral visitor`
