### ISSUE TITLE
pollenTubesQuantitySingleVisit

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#12]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** |  pollenTubesQuantitySingleVisit |
| **Definition** |  The number or enumeration value for the quantity of pollen tubes growing in the style of the flower in which the `Interaction` was recorded when exposed to a single visitor. |
| **Comments** |  Should be filled with the number of pollen tubes growing in the style after a period of multiple visits. |
| **Examples** |  `2`, `4`, `10` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Term definition:

`The number of pollen tubes growing in the style of the flower in which the Interaction was recorded when exposed to multiple visitors`

@pzermoglio:
> if you follow the definition of the class (`InteractionOutcome`), this should be "Interactions(s) were recorded

**Comment by fonturbel** [comment]
No further comments on this

**Comment by zedomel** [comment]
Same as in #35 :
**New definition**: `The number of pollen tubes growing in the style(s) of a flower exposed to a single floral visitor.`
