### ISSUE TITLE
seedMass

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#13]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | seedMass  |
| **Definition** | The mass in miligrams of mature seeds of a fruit from a flower exposed to a single visitor. |
| **Comments** |  |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Term definition:

`The mass in milligrams of mature seeds of a fruit from a flower exposed to a single visitor`

@pzermoglio:
>the total mass? the average mass?

**Comment by fonturbel** [comment]
Average mass (representing the mass o an average single seed)

**Comment by zedomel** [comment]
@fonturbel we should avoid to restrict the usage of the term to only aggregate measures (e.g. average). People can specify the type of the measurement using Darwin Core term and extensions for that. 

Is there any problem with the definition:
`The mass of mature seed(s)`??

**Comment by anselmoeco** [comment]
I think that would be better "the mass of seed(s) from a mature fruit". We have more clarity about the fruit's maturity than the seed's.

**Comment by zedomel** [comment]
**New definition**: `The mass in milligrams of seed(s) of a mature fruit from a flower exposed to a single visitor`
But I'm not sure if the fragment `from a flower exposed to a single visitor` is needed here.  It's look like more a **protocol** definition than a **measurement**. 

We should think a better way to differentiate measurements taken from exposed/bagged and single/multiple visitors.

**Comment by fonturbel** [comment]
> **New definition**: `The mass in milligrams of seed(s) of a mature fruit from a flower exposed to a single visitor`
> But I'm not sure if the fragment `from a flower exposed to a single visitor` is needed here. It's look like more a **protocol** definition than a **measurement**.
> 
> We should think a better way to differentiate measurements taken from exposed/bagged and single/multiple visitors.

I agree @zedomel the "single visit" part seems not to be necessary

**Comment by terezagiannini** [comment]
It seems to me that the last formulation is the best. I would leave "single visit" to be clear about.

**Comment by pietrokiyoshi** [comment]
I agree with @zedomel that the last part seem more related with a specific protocol (which would restrict the usage only if this protocol was followed)

**Comment by RafaelCBorges** [comment]
I believe it is important to keep that this 'seed' is the product of a single visit, as therefore that seed will be the result from the pollination provided by a known pollinator. 
Having this type of data is important to understanding the quality of the pollinator for that plant and will permit further comparison for evaluating if that plant has one, a few or several very efficient pollinators. 
@zedomel I think the current definition (The mass in milligrams of seed(s) of a mature fruit from a flower exposed to a single visitor) is very good. 
If only one seed is produced from that fruit than the value would be the mass of that single seed, if multiple seeds are produced from that visit, than I believe that the best is to have the mass of each produced seed, this would improve data usability in the long term as the user will be able to calculate the metric that most sooth his work (average, mean, standard deviation), and will also be able to count the number of seeds produced from this single visit.

**Comment by pjbergamo** [comment]
I am a bit confused here.
All other terms related to plant reproductive success (conspecific pollen grains on stigma, pollen tubes, fruit set, seed set) were not from single visit measurements.
Why only this one (and specially one that is not as often measured as the aforementioned reproductive success variables) should be measured when a flower is exposed to a single visitor?

My suggestion is to follow the edits made to all other reproductive success variables to this one here.

**Comment by arech2003** [comment]
I agree with @pjbergamo

**Comment by zedomel** [comment]
@pjbergamo  I was wondering about that too  👍 

So, to maintain the consistence with other reproductive success terms, should we change the definition to `exposed to multiple visitors`?

@RafaelCBorges and others, what is more common seed mass for `single visit` or `multiple visit`? Otherwise, we should have `single visit` and `multiple visit` **states** for every reproductive success terms. I very inclined to add a new term like `flowerState` (`exposed`, `not exposed`) or `visitationState` (`multiple`, `single`). 

Another option, since multiple visitations implies multiple **interactions**, is to create a term `numberOfVisits` (it can be 0, 1 or any other value greater than 1) and it may give the information if the flower received **multiple** or **single** visits or even **no visitation**. 

**But, if we go that way, I'm afraid that we will need to review many terms that are already defined as `multiple visits`**.

So, my suggestion to keep it simpler and in order to have a **initial** release of the standard is to follow what have been done for other reproductive success terms. We can consider to change it in future releases with we realize that we need to differentiate more precisely the **multiple** from **single** visitation states.

**Comment by RafaelCBorges** [comment]
@zedomel 
I think your suggestion to create the new term sounds very interesting. 
It would provide that information for the many terms. My suggestion would be to have the visitationState term, with three states (exposed, multiple, single). Exposed would refer to interactions collected in flowers that were not systematically followed, thus the observer only knows that it was exposed. Multiple refers to case where the observer knows about multiple visitor to that flower, and single refers to single visit events. 
Combining your suggestion to include the number of visits, it could be exposed, single, multiple, number of visits (1, 2, 3, ...). 
Just one thing, zero visits would not be included, right? The data base is for interactions, thus a flower without interactions could not be inserted, isn't it?
As previously mentioned, I think adding this information may improve data usability. 

As you pointed, however, there is the issue of other terms. By creating a term to inform the "amount" of visitors it should automatically relate to all terms in that interaction event, thus I believe other terms don´t need to mention the number of visits. (however, I did not participate in the discussion for including **multiple visits** in the other terms)

If this new term inclusion imply in a big delay, I´m ok with keeping it as multiple visits until improvement is required. 

One question though, the terms that include **multiple visits** would be left blank for single visit interaction event?
