### ISSUE TITLE
standingCropFlowerLongevity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#14]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** |  standingCropFlowerLongevity  |
| **Definition** | The elapsed time in hours or an enumerated value between the moment in which a flower opens and its senescence, describing when the standing crop measures were taken during the flower longevity. |
| **Comments** |  |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
These 3 terms are related, so they can't be fitter in a MoF extension. During the flower longevity we can have multiple values of `standingCropNectarVolume` one for each specific "time" of the flower longevity. 

Should we create an extension (class) just for nectar dynamics (i.e. `NectarDynamics`) ?

**Comment by fonturbel** [comment]
Should match flower longevity term specs

**Comment by zedomel** [comment]
Removed
