### ISSUE TITLE
flowersVisitedQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#15]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | flowersVisitedQuantity |
| **Definition** | The number or enumeration value for the quantity of flowers visited in this `Interaction`. |
| **Comments** |  |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Term definition:
`The number of flowers visited in this Interaction`

By the definition we can understand that it is possible to recorded multiple visits in one `Interaction`. But multiple visits of the same animal individual? same plant individual? Maybe we should made this more clear.

The ideia is that `flowersVisitedQuantity` works as a summary for interaction data: species `X` visits `10` flowers of species ` Y`. But we can always split this `10` visits in `10` distinct records of the same species `X` and `Y`. So, do we really need this term?

**Comment by fonturbel** [comment]
This refers to a single visit event or a period of time (e.g., 10 min)?

**Comment by zedomel** [comment]
@fonturbel  I think that the period of time will be capture by another term on Darwin Core ([**`dwc:eventDate`**](http://rs.tdwg.org/dwc/terms/eventDate) and [**`dwc:eventTime`**](http://rs.tdwg.org/dwc/terms/eventTime))

**Comment by carmensspires** [comment]
@zedomel This term refers to the number of flowers visited by a given animal (an individual) in a given period. That's right? It is a difficult measure to take on the field, but not impossible.

**Comment by zedomel** [comment]
It will be removed.
