### ISSUE TITLE
heterospecificPollenGrainsQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#16]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | heterospecificPollenGrainsQuantity  |
| **Definition** | The number or enumeration value for the quantity of heterospecific pollen grains deposited on the stigma(s) of a flower exposed to multiple visitors. |
| **Comments** |  |
| **Examples** | `435`, `600` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Term definition:

`The number of heterospecific pollen grains deposited on the stigma(s) of a flower exposed to multiple visitors`

The problem here also applies to other terms which have the statement: `multiple visitors`.  

Multiple visitors implies multiple `Interactions`. So, this term be an aggregation of multiple interactions, but the definition says that this a measure of particular flower (`of a flower exposed`). In the end, should we have multiple measurements of `heterospecificPollenGrainsQuantity` for each flower (of a particular plant?) exposed to **multiple visitors**? 

For sure the measurement is taken from each flower of a plant, independent of an `Interaction` being recorded or not. We can still have a value for this measurement without having any `Interactions` related to it. Example: 
*someone observing a flower (or not) just count the number of visits (without recording the flower visitors) and after some time, just collect the flower to count the number of pollen grains deposited by those `n` visits.*
In the example, we do not have any Interaction, as the visitors were not recorded by we still have `heterospecificPollenGrainsQuantity`. 

So, maybe it can't be related to the `Interaction` class, but instead, it should be related to the plant `dwc:Occurrence`, but I'm not sure.

**Comment by fonturbel** [comment]
We also have the coespecific pollen grains, this should be the difference between total - coespecific grains, right?

**Comment by zedomel** [comment]
Same as in #41 : 
**New definition**:  `The total number of heterospecific pollen grains deposited on a flower stigma(s)`
**Comments**: `The number of heterospecific pollen grains must be measured on a flower exposed to visitors at the end of the its anthesis`
