### ISSUE TITLE
accumlatedNectarVolume

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#18]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | accumulatedNectarVolume |
| **Definition** | The total volume in microliters of nectar accumulated at the end of a flower lifespan which was prevented from visiting |
| **Comments** |  |
| **Examples** | `5`, `10`, `5.5` |
| **Controlled vocabulary** | |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  "The nectar volume should be measured with a micro-syringe or calibrated calipers in flowers at end of its lifespan and prevented from visitation during all the lifespan (e.g. bagged). All the volume produced by the flower should be measured and reported in microliters. Protocol reference: Galetto & Bernadello 2005" |

**Comment by zedomel** [comment]
Include `inMicroliters` in  the term name: `accumlatedNectarVolumeInMicroliters`.

**Definition: **
`The total volume in microliters of nectar accumulated at the end of a flower lifespan which was prevented from visiting`

**Comment by zedomel** [comment]
@pzermoglio:
> should `microliters` be part of the name? As in `dwc:maximumElevationInMeters`

>  `which was prevented from visiting`: prevented how? or do you mean "which was not visited"? In any case, visited by whom?

**Comment by zedomel** [comment]
The term `accumlatedNectarVolume` is related to *the nectar volume **accumulated** at the end of a flower **longevity** which was **prevented from visiting***.

**accumulated**: not sufficient to capture non-accumulated measures of nectar volume; ex: *two or more measurements of nectar volume were taken during the flower longevity*.

The new term `nectarVolumeInMicroliters` will make possible to share,  in conjunction with `nectarConcentration`, multiple measurements of nectar dynamics, instead of just the volume/concentration of the accumulated nectar.
 
Term definition (proposal):
`The nectar volume in microliters at a specific period of the flower's longevity`

This definition makes no assumption or statement about to a specific period of a flower longevity (opposed to: *at the end of a flower longevity*). So, how can we specify that period using a discrete or continuous data-time representation?

**Options**:

- Use **`obis:ExtendedMeasurementOrFact`** (eMOF) class . The terms of eMOF class can be used in conjunction with an external vocabulary for plant-pollinator interactions. The term `dwc:measurementDeterminedDate` should be used to define the period of a flower longevity in which the measurement was made. Additionally, the vocabulary should includes terms like `nectar volume` and `microliters`  to be used with `obis:measurementTypeID` and `obis:measurementUnitID`.

- Add a new term to share the specific date-time when a nectar volume measurement was made.

**Comment by fonturbel** [comment]
No further comments on this entry.

**Comment by zedomel** [comment]
Same as in #21 
Not changed
