### ISSUE TITLE
cospecificPollenGrainsQuantitySingleVisit

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#2]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | cospecificPollenGrainsQuantitySingleVisit |
| **Definition** | The number or enumeration value for the quantity of coespecific pollen grains deposited on the flower's stigma(s) exposed to a single visitor at the end of flower anthesis. |
| **Comments** |  |
| **Examples** |  `223`, `100` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Definition: 
`The number or enumeration value for the quantity of coespecific pollen grains deposited on the flower's stigma(s) exposed to a single visitor at the end of flower anthesis`

Issues: 
- This measurement is the average number of pollen grains in the stigmas or an absolute measurement for each stigma in a flower? In other words, **one measurement per flower**  or **multiple measurements per flower** (*one per stigma*).
- The sentence `single visitor` in the definition can be removed? As an **Interaction** is defined to be a **visit** of a particular **Animal** to a particular *flower* of a **Plant**, is it already implicit in an **Interaction** record? How can we differentiate from flowers which are exposed to a single visitor (then bagged) from flowers which are not bagged and received visitations and pollen depositions from many pollinators (multiple **Interactions**)?
- The sentence `at the end of flower anthesis` makes explicit that the pollen grains quantity must be measured at a specific time in the flower longevity. Should we make it more general? Can this measurement be made before flower anthesis or during other period of flower longevity? 

The definition looks very tied to some protocol. How people are doing it in general?

**Comment by fonturbel** [comment]
No comments on this term

**Comment by paf1306** [comment]
I suggest "The number of conspecific pollen grains deposited on the flower's stigma(s) exposed to a single visitor at the end of flower anthesis". Nothing else to add.

**Comment by zedomel** [comment]
**New definition**: `The number of conspecific pollen grains deposited on the flower's stigma(s) exposed to a single visitor at the end of flower anthesis`
