### ISSUE TITLE
flowerSexuality

### ISSUE THREAD

**Issue by pzermoglio** [BioComp-USP/rebipp-data-standard#20]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | flowerSexuality |
| **Definition** | The sexuality of the flower which this `Interaction` was recorded regarding to the presence of both (bisexual) stamens (male organs) and pistils (carpels) (female organs), or unisexual, with only male (staminate flower) or female (pistillate or carpellate flower) functional organs. |
| **Comments** |  |
| **Examples** | 'bisexual', 'male', 'female' |
| **Controlled vocabulary** | bisexual, male, female |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
I suggest the following controlled vocabulary: monoecious (male); monoecious (female); dioecious

**Comment by Mardiore** [comment]
The definition is confusing. I suggest: The sexuality is based in the presence of the fertile whorls within the flower, may be bisexual, with both  stamens (male organs) and pistils (carpels) (female organs), or unisexual, with only male (staminate flower) or female (pistillate or carpellate flower) functional organs.

I suggest to Examples and to Controlled vocabulary: Bisexual, Staminate flower and Pistillate flowers. These terms are more used in the literature (in the area of anatomy, for example, the terms male and female are usually not employed).

**Comment by Mardiore** [comment]
> I suggest the following controlled vocabulary: monoecious (male); monoecious (female); dioecious

The definition is related to the sexual expression of the flower and not of the individual of a population.

**Comment by zedomel** [comment]
Accepted @Mardiore suggestion to the controlled vocabulary. The definition will be merged too.
