### ISSUE TITLE
pollinate

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#22]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** |  pollinate |
| **Definition** | Indicates if the animal touches the reproductive structures (anthers and stigmas) of a flower during the visit (pollination). |
| **Comments** | Recommended best practice is to use values which can be converted to boolean (`TRUE` or `FALSE`) such as `0`/`1`, `true`/`false`, `yes`/`no`. |
| **Examples** |  `yes`, `no`, `0`, `true` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by carmensspires** [comment]
By definition we are wondering if the floral visitor is a potential pollinator. So I suggest changing the label to:
- If you can use interrogation: Pollinator? 
  Or
- Pollinates

Is there a letter or word limit for labels?

**Comment by zedomel** [comment]
@carmensspires  we should avoid to use special characters in term's label.

But, the discussion that I want to bring here is:

- This term is really needed? Or can we just use the value `pollinates` in the `Interaction Type` term? 

The problem that I see is that pollination is not inferred at the moment of the observation, but instead, it will be inferred later when the visitation proves to transferring pollen and fruit development. But the definition, simplify it to be `touches the reproductive structures`, that in fact is something that can be observed in the field, and so, I wondering if we can just **eliminate** this term and create a value `pollinates` in the controlled vocabulary for `Interaction Type`.

**Comment by fonturbel** [comment]
Why not have two options: flower visitor or pollinator.
The first one indicates that the animal visits the flower but we don't know if it actually pollinates or not
The second indicates that we have evidence that the animally do pollinate the flower

**Comment by lgcarvalheiro** [comment]
an alternative (for this term) that allows for doubt on the efficiency of pollination: touches the reproductive structures?

**Comment by zedomel** [comment]
@lgcarvalheiro I like the ideia. 

So, I propose to change the term **label** to `touchesReproductiveStructures`, and the controlled vocab should be `true` and `false`

Then, the term definition can be: `Indicates if the animal touches the reproductive structures (anthers and stigmas) of a flower during visitation.` or `Indicates if the animal touches the reproductive structures (anthers and stigmas) of a flower during the interaction.`

**Comment by pjbergamo** [comment]
I agree with changing to touchesReproductiveStructures and the first definition (...of a flower during visitation).
I could not find the term Interaction Type to check if it overlaps with this one here.

**Comment by zedomel** [comment]
@pjbergamo we do not have a term `Interaction Type`, probably we will use one [`dwc: relationshipOfResource`](http://rs.tdwg.org/dwc/terms/relationshipOfResource). But it depends on the data model. For now, we have a controlled vocab for `dwc:relationshipOfResource` as defined in the document: [https://docs.google.com/document/d/1MM5Yh2l0Zkbq708vh6L1KRJEDqfhOQHBobVyFPblGL0/edit#heading=h.yk3lixnmphkr](https://docs.google.com/document/d/1MM5Yh2l0Zkbq708vh6L1KRJEDqfhOQHBobVyFPblGL0/edit#heading=h.yk3lixnmphkr).
 In that document you will see that we already have the terms `pollinates`  and `pollinated by`, so this term here appears redundant.

**Comment by carmensspires** [comment]
I agree with with changing to touchesReproductiveStructures.

**Comment by Mardiore** [comment]
I agree with touchesReproductiveStructures

**Comment by zedomel** [comment]
Term's label will be changed to `touchesReproductiveStructures` and the definition to `Indicates if the animal touches the reproductive structures (anthers or stigmas) of a flower during visitation`
