### ISSUE TITLE
standingCropNectarConcentration

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#24]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | standingCropNectarConcentration |
| **Definition** | The concentration of nectar, as a percentage of sugar, available to visitors at a given time of a flower longevity. |
| **Comments** |  |
| **Examples** | `25`,`75` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by carmensspires** [comment]
I have nothing to add.

**Comment by anselmoeco** [comment]
The same suggestion of exclusion made in #25.

**Comment by zedomel** [comment]
Removed
