### ISSUE TITLE
standingCropNectarVolume

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#25]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | standingCropNectarVolume |
| **Definition** | The total volume in microliters of nectar available to visitors at a given time of a flower longevity. |
| **Comments** |  |
| **Examples** | `5`, `10`, `8.5` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
OK with this one

**Comment by carmensspires** [comment]
I have nothing to add.

**Comment by pjbergamo** [comment]
I am not the biggest fan of including standing crop in the database.
Standing crop is a nectar measurement in an open flower (therefore that was exposed to floral visitors) at any time.

As I said in #21 , nectar is extremely variable even within a plant individual. Standing crop is a method on which there is no control of any variable and people measure it at any given time. Therefore, standing crop is hardly comparable even between populations of the same species. I see no point for it in a database and for syntheses.

**Comment by anselmoeco** [comment]
I agree with @pjbergamo, I think that for this first version at least this descriptor can be excluded.

**Comment by zedomel** [comment]
It will be removed
