### ISSUE TITLE
stigmaticArea

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#26]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | stigmaticArea |
| **Definition** | The total surface area in square millimeters of the stigma(s) of a flower. |
| **Comments** |  |
| **Examples** | `10`, `25` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
OK with this one

**Comment by carmensspires** [comment]
I have nothing to add.

**Comment by Mardiore** [comment]
it's OK
