### ISSUE TITLE
styleLength

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#27]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | styleLength |
| **Definition** | The average length from the base to the tip of the style(s) of flower(s) of this plant `Occurrence` |
| **Comments** |  |
| **Examples** | `12.5`, `6.5`, `20.0` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
OK with this one

**Comment by carmensspires** [comment]
I have nothing to add.

**Comment by zedomel** [comment]
I would suggest to remove `average` from the definition, something like:
`The length from the base to the tip of the style of flower`

**Comment by Mardiore** [comment]
I agree

**Comment by anselmoeco** [comment]
I agree with the @zedomel suggestion.

**Comment by zedomel** [comment]
**New definition**: `The length from the base to the tip of the style of the flower`

An length unit must be specified in the definition. Millimeters?
