### ISSUE TITLE
animalPlaceOfContact

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#28]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | animalPlaceOfContact |
| **Definition** | A list (concatenated and separated) of places (i.e. body parts) of the animal body that contacts its interacting partner during an `Interaction`. |
| **Comments** | Recommended best practice is to separate the values in a list with space vertical bar space ( `|` ) and to use a controlled vocabulary. |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
This needs a further revision from a specialist

**Comment by carmensspires** [comment]
As we are trying to make inferences about which floral visitors would have the potential to be pollinators, I believe that we should specify in the definition the parts of the flower that are touched.

Definition proposals:
A list (concatenated and separated) of places (i.e. body parts) of the animal body that contacts anther and stigma of its interacting partner during an Interaction.

Or

A list (concatenated and separated) of places (i.e. body parts) of the animal body that contacts anthers and stigma during an Interaction.

Or

A list (concatenated and separated) of places (i.e. body parts) of the animal body that contacts reproductive parts of the flower during an Interaction.

**Comment by zedomel** [comment]
@carmensspires  I don't know if we need to include the parts of the flower in the definition.

It will restrict the usage of the term to only floral parts, opposed to allow a generic usage where the animal touches another parts of the plant (leaf, trunk, etc). 

By the way, the floral parts when touched must be specified using the term `plantPlaceOfContact`(#31).  Using the term `placePlaceOfContact` one can specify values as: `anther` or `stigma`.

**Comment by Mardiore** [comment]
If the intention is to record interactions (regardless of whether they result in pollination or not) I agree that it is better not to mention specific parts of the plant, such as floral structures.

**Comment by anselmoeco** [comment]
I agree with @zedomel and @Mardiore. However, if we want to at least refer to the interactions between animals and plants, we could then use something like: "A list (concatenated and separated) of places (i.e. body parts) of the animal body that contacts the plant partner during an Interaction".

**Comment by zedomel** [comment]
**New definition**: `A list (concatenated and separated) of animal's body parts that contacts the plant`

Removed `partner during an Interaction` since it the **interaction** with a plant is implicit here (`Interaction` class)
