### ISSUE TITLE
attractiveStructureColor

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#29]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | attractiveStructureColor |
| **Definition** | The predominant color of the plant's structure which visually attracts the visiting animal. |
| **Comments** | "Recommended best practice is to separate the values with space vertical bar space ( | ) and sort them in the same order of the structures listed in `attractiveStructure`. Recommended best practice is to use a controlled such as Plant Trait Ontology (TO) |
| **Examples** | `blue`, `red \| yellow`, [`http://purl.obolibrary.org/obo/PATO_0000951`](http://purl.obolibrary.org/obo/PATO_0000951) |
| **Controlled vocabulary** | [Phenotype And Trait Ontology](http://purl.obolibrary.org/obo/PATO_0000014) |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Maybe it would be better to copy color levels from the Phenotype and Trait Ontology webpage to clarify in the controlled vocabulary what are the available options (and prevent artistic creativity with 64 million color options)

**Comment by carmensspires** [comment]
This label could not be included in the floralAdvertisement#42 ?

Why separate color from other characters that attract floral visitors, such as volatile chemicals?

**Comment by zedomel** [comment]
@fonturbel good suggestion, I will do that when we are done with the standard.

@carmensspires I was thinking about that too. Why are we give more emphasis to the visual attractants than others attractants?

But answering your question of using this in `floralAdvertisement ` #42. The term `floralAdvertisement` should be used to specify the a list of structures that attracts the visitors, which can include `colored structured` (but we should review the controlled vocab of #42 to include specific structures as `petal`, `sepal` etc.). We should not use the term `floralAdvertisement` to specify **the color of the attractive structure** (example:  `blue petal`), otherwise we will mixing two concepts (the color of the attractant structure and the attractant structure). Additionally, it will implies that we have to define a very long controlled vocab for `floralAdverstisement` including term like `blue petal`, 'yellow petal`, `red petal`, `blue sepal`, `red sepal`, thus, all combinations of color x structures.

Also, this term and `attractiveStructure` (#8) are related to the animal (which structures from all possible floral attractants (`floralAdvertisement`) are used by this specific animal to find the flower).

There is emphasis to visual structures since we have term like `attractiveStructure` #8

**Comment by pjbergamo** [comment]
@zedomel @carmensspires 
The reason to give more emphasis to visual attractants is because it is much more simple to obtain flower colour data than fragrance data.

People often report the colour of the flowers, but not the specific components of fragrances (which are difficult to obtain).

**Comment by zedomel** [comment]
@pjbergamo  OK I understand. But, if other attractants are difficult to obtain, do we really need a term for capture them like `floralAdvertisement` (#42 )? 
How many studies have captured this? How often those values are captured in fields? Could provide a example of dataset with attractants other than visual?

thanks

**Comment by pjbergamo** [comment]
The presence of other attractants and some rough qualitative characteristics of them can be evaluated, such as presence of perfurme during the day or the night. What is difficult to obtain is the detailed components of the fragrance bouquet of a flower. Thus, there is no need for a detailed term for fragrance.

**Comment by zedomel** [comment]
@pjbergamo So,  `floralAdvertisement` can be filled with values that do not have any support evidence of **attraction**? In other words, how could someone know that was the perfume that really attracts the visitor and not some other structure/compound?  
I'm just trying to understand it, because it makes a lot of difference calling a structure as **attractant** instead of just say the  **a flower** has perfume, not?

**Comment by pjbergamo** [comment]
@zedomel Ideally everything should be tested experimentally. However, we cannot enforce such constraint otherwise the database will be seriously limited to a handful of examples.

What many studies do is to study the flower ("floral biology"): measure its parts and identify **potential** attractants. In the end, many studies do provide a list of potential attractants (e.g. this plant produces red bracts, yellow flowers and emit a sweet perfume during the day). This is not completely terrible on itself, as we know that human-perceived color and fragrances may indeed attract flower visitors.

However, this is different to state: the yellow coloration function is **to attract Apis mellifera**. My concern in moving this term to the Interaction class was to link each attractant to a specific visitor - this would need everyone to make huge assumptions to fill the term.

By keeping it in the plant class, we can therefore use more relaxed definitions not dependent on experiments.

**Comment by zedomel** [comment]
@pjbergamo please, see my last comment on #42

**Comment by Mardiore** [comment]
I agree whih @zedomel, I think the two labels are necessary, one indicates the color (attractive) and the other the structure (petal, stamens ...#8) that attracts.

**Comment by zedomel** [comment]
The term will be moved to `FlowerTrait` as it represents **potential** attractants instead of the **actual** attractants of a specific *Interaction*. 
**New label:** `visuallyAttractiveStructureColor`
**New definition:**  `The predominant color of the flower's structure which act as a visual attractant`
