### ISSUE TITLE
fertilizedOvulesQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#3]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** |  fertilizedOvulesQuantity |
| **Definition** | The number or enumeration value for the quantity of fertilized ovules in a flower which the `Interaction` was recorded. |
| **Comments** | Should be filled with the number of pollen tubes growing in the style and fertilizing ovules after one visit. |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
The same issues of `cospecificPollenGrainsQuantitySingleVisit` #2 . 
The definition says: 
`The number or enumeration value for the quantity of fertilized ovules in a flower which the `Interaction` was recorded`.

Here the **Interaction** is present in the definition, but we don't know if the flower was bagged or not before the **Interaction** (*single visit* or *multiple visits*?).

The *single visit* and *multiple visits* are states of the flower, and not the state of the **Interaction**, as a **Interaction** is always a single visit (or not?). Then, we need to know if a particular flower visited by a pollinator was prevented from other visitors (bagged) or not.

**Comment by fonturbel** [comment]
No comments on this term

**Comment by zedomel** [comment]
**New definition**: `The number of fertilized ovules in a flower`
