### ISSUE TITLE
collectingBodyPartLength

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#30]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | collectingBodyPartLength |
| **Definition** | The length in millimeters of the body part used to access the floral resource. |
| **Comments** | The `collectingBodyPart` should be provided in order to access which body part this length is related to. |
| **Examples** | `12`,  `100` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Is this truly necessary?

**Comment by carmensspires** [comment]
@fonturbel In cases of collection of nectar in tubular flowers, the length of the beak (hummingbirds), the tongue (bees) is important. And based on this character, we can separate floral visitors from possible pollinators.

**Comment by Mardiore** [comment]
I think it is necessary to be more specific, to mention which parts can be measured, as "tongue length, beak length, leg length".

**Comment by anselmoeco** [comment]
I agree with @Mardiore. In this case, for more explicit terms this information could be divided into two terms: (i) collectingBodyPart; and (ii) collectingBodyPartlength. I know that it is not desirable to propose new terms, but it seems complicated to have the organ's size data for different visitors without knowing which organ was measured clearly.

**Comment by zedomel** [comment]
@Mardiore  and @anselmoeco  we already have a term for that `collectingBodyPart` (#9), so, no new term is needed.

Not changed.
