### ISSUE TITLE
plantPlaceOfContact

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#31]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | plantPlaceOfContact |
| **Definition** | A list (concatenated and separated) of places (i.e. structures) in the plant that contacts its interacting partner during an `Interaction`. |
| **Comments** | Recommended best practice is to separate the values in a list with space vertical bar space ( `|` ) and to use a controlled vocabulary. |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
I am not sure what this term is referred to...

**Comment by carmensspires** [comment]
I was also in doubt, as well as @fonturbel... 

Does this term refer to the parts of the flower that are touched by the floral visitor at the time of the visit to collect some resource? If so, better switch to flowerPlaceOfContact. And the answer options would be the main parts of the flower: anthers, stigma, petals....

**Comment by zedomel** [comment]
@carmensspires  and @fonturbel I believe that the concept here is to capture all the possible plant structures/organs that an animal touches during visitation. It can be very specific as floral parts (`anther`, `stigma`, `petals`) or more general as whole plant structures (`flower`, `leaf`). 

Maybe we should change the definition to:

`A list (concatenated and separated) of structures or organs of the plant touched by an animal`
Then, we can adjust the **Comments** to explain that it can be filled with specific floral parts or more general plant structures. As well as, we should provide examples with both scenarios.

**A controlled vocabulary of plant structures/organs should also be provided here!**

Putting the definition this way, I'm wondering now if we still need the term `pollinate` (or `touchesReproductiveStructures`) #22. Since this term is filled with reproductive structures of the plant is possible to infer that the animal touches the reproductive structures of the flower, and so, *"pollinates"* it (as defined in #22).

**Comment by Mardiore** [comment]
If the interaction is between plant and pollinator, this term should be related only to the reproductive organs. If the interaction is pollination, the other parts of the plant do not matter. @carmensspires I agree with flowerPlaceOfContact.

**Comment by zedomel** [comment]
Change term's label to `flowerPlaceOfContact`. But the conflicts with #22 is not resolved.
