### ISSUE TITLE
resourceCollected

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#32]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | resourceCollected |
| **Definition** | A list (concatenated and separated) of floral resources used or removed by an animal from a flower during an `Interaction`. |
| **Comments** | Recommended best practice is to separate the values in a list with space vertical bar space ( `|` ) and to use a controlled vocabulary. |
| **Examples** | `pollen`, `pollen \| nectar \| oil`, `ovules` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Maybe it should match the "reward" term??

**Comment by carmensspires** [comment]
I agree with the definition "A list (concatenated and separated) of floral resources used or removed by an animal from a flower during an Interaction."

**Comment by zedomel** [comment]
@fonturbel for while this term differs from `floralReward` #43 by which the `floralReward` is a term to specify all **rewards** offered by a plant species to visitors (which may or may not include the **resource being collected** here). On other hand, the term `resourceCollected` is specific to a particular interaction (it requires an observation of the visitor collecting the resource).

I'm just wondering, if all **collected resources** are also **rewards** and also if all **rewards** are possibly **resources to be collected**. If so, then the term `floralReward` may be **removed** from the standard in favor of simplicity. Since, the **rewards** can be inferred by aggregating all the **interactions data** which specify a value for the term `collectedResource`.

Otherwise, same as for #42  and #8 , if we want to be able to capture literature data, that is not related with the a particular interaction, animal or plant occurrences, then we need separate term for that as we have now. But, doing that I feel that we are mixing things, and also adopting the wrong base standard (Darwin Core is based on **Occurrence** not **Taxon**)!

I need more discussions about it. Maybe having a virtual meeting to discuss these issues.

**Comment by cepnunes** [comment]
The use of the term Reward to designate the resources collected by floral visitors and pollinators is controverse, while the use of the more general term, Resource, is less controverse as it does not imply in assuming and intentionality to both plants and pollinators.

Thus, I agree that this term should be merged to the floralReward term, with a definition slightly different of both current definitions: "A list (concatenated and separated) of floral resources collected an animal visitor or pollinator from a flower during an Interaction."

Additionally, it is important to have in mind which term related to the Animal would differentiate it into pollinator or non-pollinating floral visitor.

**Comment by pjbergamo** [comment]
@zedomel People use resource and reward interchangeably. I agree with @cepnunes that resource is less controversial.
 
I would say that in most cases aggregating the interactions will indeed end in a list of all resources offered by a flower (which is the point to remove the floralReward term). My only concern goes to cases on which no resources are offered (deceptive species)

**Comment by zedomel** [comment]
@pjbergamo  so we should have a way to document that **no resources** were collected by a visitor? Maybe the controlled vocab of this term should include `none` or something similar?

**Comment by pjbergamo** [comment]
@zedomel This may be a solution. Maybe the controlled vocab should be very precise, something as: "no resources offered (deceptive pollination)".

**Comment by Mardiore** [comment]
I suggest including resin in the examples. It is necessary to exclude ovules (this is not a resource offered). In "pollen | nectar | oil", I suggest excluding oil, because oil flowers do not offer nectar.

**Comment by anselmoeco** [comment]
I think it is more appropriate to focus on resources and not rewards, so we avoid misunderstandings as well. I liked @pjbergamo's last suggestion to solve the problem.

**Comment by zedomel** [comment]
`flowerReward` will be removed in favor of this term.
