### ISSUE TITLE
verticalStratum

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#33]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | verticalStratum |
| **Definition** | The vertical layering (i.e. stratum) of a habitat where the `Interaction` occurs. |
| **Comments** | Recommended best practice is to use a controlled vocabulary. |
| **Examples** | `canopy`, `understory`, `forest floor` |
| **Controlled vocabulary** | `canopy`, `subforest`, `herbaceous stratum` |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
I found a possible controlled vocabulary for this term in [ENVO](https://sites.google.com/site/environmentontology/) ontology:

The [Vegetation layer](http://purl.obolibrary.org/obo/ENVO_01000355) defines the terms:
- `canopy`:
   - `crop canopy`.
   - `forest canopy`.
   - `woodland canopy`
- `herb and fern layer`
- `litter layer`
- `shrub layer`
- `understory`
 
Can we use that vocabulary instead of define a new one?

**Comment by fonturbel** [comment]
I suggest the following controlled vocabulary: canopy; sub-canopy; understory

**Comment by anselmoeco** [comment]
This term will be applied only for entries made in the forest environment, is it so? Perhaps that term was not fundamental now.

**Comment by carmensspires** [comment]
When I saw the term without the definition, I thought about the location of the flower that received the pollinator's visit in relation to the plant (individual): upper third, middle third and lower third of the plant, when it comes to herbaceous plants, etc. 

I agree with @anselmoeco that this term will will be applied only for entries made in the forest environment and it is not fundamental now.

**Comment by pjbergamo** [comment]
I agree with @anselmoeco and @carmensspires

**Comment by zedomel** [comment]
Not useful at this moment. It will be removed.
