### ISSUE TITLE
fruitSet

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#34]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | fruitSet |
| **Definition** | Percentage of flowers exposed to floral visitors during anthesis that set fruit. |
| **Comments** |  |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Can we have **fruitset** from flowers not exposed  (i.e. bagged)? If so, should we change the term definition to be general enough to allow sharing fruitset from bagged flowers? 

In #41  I have suggested the creation of a **new term** `flowerState`, but perhaps it should be something like `flowerTreatment`, since the *exposed*, *bagged*, etc. conditions are different treatments for collecting the same measurement.

I have found some examples of **fruit set** that are not directly related to the `Interactions`:

- [https://figshare.com/articles/Acai_fruit_production_data/6032789](https://figshare.com/articles/Acai_fruit_production_data/6032789)
- [https://scielo.figshare.com/articles/Pollination_biology_of_melittophilous_legume_tree_species_in_the_Atlantic_Forest_in_Southeast_Brazil/7101311?file=13065986](https://scielo.figshare.com/articles/Pollination_biology_of_melittophilous_legume_tree_species_in_the_Atlantic_Forest_in_Southeast_Brazil/7101311?file=13065986)

So, it is possible that a **fruit set** will not have any `Interaction` linked to it. But it can represent an outcome from multiple **interactions** that occurred in a plant or a set of plant individuals. How use it in conjunction with `Interaction` class and other terms?

**Comment by fonturbel** [comment]
Definition proposal: "Proportion of the pollinated flowers that yielded fruits"

**Comment by cepnunes** [comment]
I agree with the proposal of @fonturbel , which makes the definition more general.

**Comment by joiceiamara** [comment]
I agree with @fonturbel

**Comment by carmensspires** [comment]
I also agree with @fonturbel proposal.

**Comment by zedomel** [comment]
**New definition**: `Proportion of the pollinated flowers that yielded fruits`
