### ISSUE TITLE
pollenTubesQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#35]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | pollenTubesQuantity |
| **Definition** | The number or enumeration value for the quantity of pollen tubes growing in the style of the flower in which the Interaction was recorded when exposed to multiple visitors. |
| **Comments** | Should be filled with the number of pollen grains removed from the anthers after one visit. |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Change term definition to:  `The quantity of pollen tubes growing in the style of the flower in which the Interaction was recorded when exposed to multiple visitors.`

This definition is different from some similar measurements. Here, the `Interaction` is explicit in the definition, meaning that this measure must to be made in the same flower where the interaction occurred. So, the `Interaction` must also be recorded. Can we change it, so this relationship with `Interaction` can be removed? Then, we will have a general term for the **quantity of pollen tubes growing in a particular flower` that can or can not be linked to an `Interaction`.

Also, as in #41  should the **multiple visitors** be removed and replace by the adoption of a **new term** `flowerState`?

Can someone provide examples of usage of this term?

**Comment by Filipi-Soares** [comment]
Hello, @zedomel! I found this paper that might be useful to provide some **examples**: 
Stavert, J.R., Bailey, C., Kirkland, L. et al. Pollen tube growth from multiple pollinator visits more accurately quantifies pollinator performance and plant reproduction. Sci Rep 10, 16958 (2020). https://doi.org/10.1038/s41598-020-73637-5.
In the Results section the authors present a graph with the number of pollen tubes by stylar region of the flower.

**Comment by zedomel** [comment]
@Filipi-Soares  thank you for your contribution.

But, maybe we need more examples of datasets (raw data) than summarised data as we found on papers. 

Papers are very useful to understand the protocols, the process of collecting data, and types of analysis that people usually do. 

I have used [Google Dataset Search](https://datasetsearch.research.google.com/) to find examples of datasets. But it will be very nice to have examples from this community.

I will take a look into the paper and see what we can learn from that.

Thanks very much.

**Comment by CADDE-CENTRE** [comment]
Oi Salim, aqui é o Andre, tou testando

**Comment by fonturbel** [comment]
I have no comments on this one

**Comment by cepnunes** [comment]
@zedomel , in this case I would simplify the definition to: "The quantity of pollen tubes growing in the style of the flower in which the Interaction was recorded. " And leave the information about the visitors (multiple or single) to come from other existing fields.

**Comment by zedomel** [comment]
@cepnunes, is it always possible to link the flower with the `Interaction`? Or sometimes we have the number of pollen tubes but no ways to know which `Interaction`s were responsible for that outcome?

**Comment by pjbergamo** [comment]
Sorry, but we are running in circles here. The discussion in #41 applies here (as I also mentioned in #37 ). All reproductive success variables may follow what was discussed in #41 : #36 , #34 , #10 , #37 #11

**Comment by anselmoeco** [comment]
I agree with @pjbergamo. Also, the reproductive success variables could be included in the solution that @zedomel  is looking for variable # 55 ovuleQuantity: "Maybe, we will have to use separated terms for specifying if a measurement if an individual measurement or an aggregate measurement (e.g. average)".

**Comment by carmensspires** [comment]
I cannot contribute to this topic....

**Comment by zedomel** [comment]
Based on discussions #41, #37, #36, #34, #10 and #11 the new definition should be:
`The number of pollen tubes growing in the style of a flower exposed to multiple floral visitors.`
