### ISSUE TITLE
removedPollenGrainsQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#36]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | removedPollenGrainsQuantity |
| **Definition** | The number or enumeration value for the quantity of pollen grains removed from the anther(s) of a flower exposed to multiple visitors. |
| **Comments** |  |
| **Examples** | `156`, `350` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Change term definition to: `The quantity of pollen grains removed from the anther(s) of a flower exposed to multiple visitors`.

Can we do the same as in #41 and use a term `flowerState` to indicate the **multiple visitors** (= exposed) state of the flower?

This is absolute measurement! So we should have one *value* for each flower, and not an average/summarised value. 

Can someone provide examples of usage of this term?

**Comment by fonturbel** [comment]
Are we able to measure this in the field? how many studies that this information?

**Comment by cepnunes** [comment]
@zedomel , like in some other terms (like #37 ), I believe that this term only make sense when in relationship to another measurement, such as total amount of pollen per flower. Moreover, I believe very few studies present this data, but with the methods for counting pollen grains becoming easier and more accessible, there will be more studies with this information in the future.

**Comment by zedomel** [comment]
@cepnunes  if it is difficult to measure it now, maybe it should removed from this **first** version of the standard. It can be added later if people find it to be useful.

@fonturbel already haas pointed out his opinion. Let's see what other think about **remove** this term.

**Comment by joiceiamara** [comment]
If there is a perspective to have more data on this subject, I think we should keep this entry.

**Comment by anselmoeco** [comment]
I agree with @joiceiamara and part of the comment of @cepnunes that this term is related to the total amount of pollen per flower. 
Another point is that the studies that measure this descriptor make the data available by flower, or by groups of anthers of the same flower (e.g. larger or smaller anthers), or even by anther. So it would be good to avoid this misunderstanding in the definition of that term.

**Comment by carmensspires** [comment]
I agree with the change in the term definition to: The quantity of pollen grains removed from the anther(s) of a flower exposed to multiple visitors.

**Comment by zedomel** [comment]
@joiceiamara and @anselmoeco  I'm not saying to complete remove this term from the vocabulary. As any other standards and vocabularies, it will never be completed/finished. 
Standards evolve according to different aspects and needs of the community which adopts it. So, it will have many versions as need to cover the use cases when properly proved to be useful for a considerable number of people. 

As @fonturbel  and @cepnunes  have pointed, if few studies will present this data, maybe we can wait until people come to this community and ask to add a term like this one.

On other hand, if we decided to keep this term, it looks that we need to add a new term `pollenGrainsQuantity` in order to specify the `total number of pollen grains found in the anther(s) of a flower`.  However, this will bring another complexity (the same that we have for other terms): this is an absolute or average measurement? What is the unit `flower`, `flowers`, `larger anthers`, `a specific anther`?

**Comment by fonturbel** [comment]
> @joiceiamara and @anselmoeco I'm not saying to complete remove this term from the vocabulary. As any other standards and vocabularies, it will never be completed/finished.
> Standards evolve according to different aspects and needs of the community which adopts it. So, it will have many versions as need to cover the use cases when properly proved to be useful for a considerable number of people.
> 
> As @fonturbel and @cepnunes have pointed, if few studies will present this data, maybe we can wait until people come to this community and ask to add a term like this one.
> 
> On other hand, if we decided to keep this term, it looks that we need to add a new term `pollenGrainsQuantity` in order to specify the `total number of pollen grains found in the anther(s) of a flower`. However, this will bring another complexity (the same that we have for other terms): this is an absolute or average measurement? What is the unit `flower`, `flowers`, `larger anthers`, `a specific anther`?

Thus, we can left this term in the freezer for a while and see if it's worthy of being included in the next iteration

**Comment by terezagiannini** [comment]
I agree with the last commentary of @fonturbel

**Comment by pietrokiyoshi** [comment]
I think the trend is for this to become more common to be measured in the future. Should we wait just because it is not sampled as often right now? I think adding the total number of pollen, and making an effort to define at what scale (anthers, flowers) this should be measured/reported at may be worthwhile (although I personally don't really work with these estimates myself).

**Comment by RafaelCBorges** [comment]
Agree with @fonturbel and @terezagiannini, I don´t see this term as required in the short term, if the community requires it in the long term (when a realistic amount of this data is available) it can be inserted.  
As pointed by @zedomel there are several complexities in keeping it now, but there seems to be almost no usability, as there is almost no data availability and no real example has been provided.

**Comment by pjbergamo** [comment]
Maybe I am biased here because I do measure pollen grain removal - although I have not published anything with these data yet...
The issues here can be solved as the issues raised in conspecific pollen grains on stigmas, pollen tubes, etc. Here, the relevant data would be the percentage left or removed (just chose one and go with it) - e.g. 40% pollen grains removed (or 60% remained) in a flower.
My suggestion is to keep it at flower level (in other words, pollen removal estimate coming from all anthers, which would cover the majority of the cases - in some flowers it is just impossible to estimate pollen removal anther per anther).

**Comment by zedomel** [comment]
@pjbergamo  if we decide to maintain it at flower level then it becomes much simpler to handle. The new definition can be:

**New definition**: `The total number pollen grains removed from the anther(s) of a flower`.
**Comments**: `The number of pollen grains must be provided for a flower which has been exposed and accessible to multiple floral visitors. The number of pollen grains must encompasses all anthers of a flower`

Does it good?
