### ISSUE TITLE
seedSet

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#37]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | seedSet |
| **Definition** | Number of mature seeds of a fruit from a flower exposed to a single visitor. |
| **Comments** |  |
| **Examples** |  |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Missing examples.

The definition make an assertion to a particular fruit of particular flower, so we should have one `seedSet` per flower. Additionally, the **single visitor** state implies only *one* `Interaction`. And what about flowers exposed to **multiple visitors**? Seed set does not apply ?

The seed set may or may not be linked to an `Interaction`, as we can quantify the seed set without recording the `Interaction`. So, maybe we should remove the **single visitor** from the definition and use this term em conjunction with a **new term** `flowerState` as describe in #41 . Then it will works for **single** and **multiple** visits and also with no visit at all (e.g. interactions not recorded; parthenocarpy: `seedSet`= `0`?).

Can someone provide datasets with examples of usage of this term?

**Comment by fonturbel** [comment]
Uhmm the "single visitor" part is troubling. Why not "the number of seeds produced in per fruit after flower pollination"

**Comment by zedomel** [comment]
@fonturbel yes **single visitor** can be a problem. The definition you suggested looks better, since it will capture both cases **single visitor** and **multiple visitors**, I just have a comment regarding to **pollination** in the definition. You would suggest to change it to:
`Number of mature seeds produced in a fruit`

**Comment by pjbergamo** [comment]
@zedomel The discussion we had in conspecific pollen grains (#41 ) applies to all terms about plant reproductive success. Thus, all terms could follow the baseline definition we discussed in #41 : This one here; fruitSet ; pollenTubesQuantity; removedPollenGrainsquantitity ; heterospecificPollenGrainsQuantity

**Comment by cepnunes** [comment]
@zedomel I don't know if it would help or just make the data insertion form too more complicated, but I believe seedSet as well as other terms (listed by @pjbergamo) could be split in at least three boxes: one with the absolute number of the trait measures, one with the number of flowers observed for this entry, and other with a time measures (which could vary from minutes to a whole flowering season). As an example for seedSet, we could have something like [243] seed(s) per [1] fruit(s) per [1] flowering season. In this case, the number of seeds would be a number as well as the other two boxes. The box with the time measure would then have to be followed by another box with controlled vocabulary if we want to include time measurements other than a single flowering season.

**Comment by pjbergamo** [comment]
@cepnunes For synthesis purposes, the important data are: average, variation (best always standard deviation) and number of samples. 
If it is clear that one should complete the database with raw data (i.e. each seed set data measured for each individual instead of  an average seed set for the population), all these data can then be retrieved afterwards.

**Comment by carmensspires** [comment]
@zedomel Seed set does apply to multiple flower visitors. I agree with definition proposal by @fonturbel "the number of seeds produced in per fruit after flower pollination".

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
**New definition**: `Number of seeds of a mature fruit exposed to a single flower visitor`

We will maintain the **single visitor**  based on discussion we had on (#41). 
Just changing **mature seeds** to **mature fruit** according to the @anselmoeco 's [comment](https://github.com/BioComp-USP/rebipp-data-standard/issues/13#issuecomment-788567416) in #13
