### ISSUE TITLE
antherDehiscenceType

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#38]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | antherDehiscenceType |
| **Definition** | The physical mechanism of anther dehiscence (release of the pollen grains) of the recorded plant species. | 
| **Comments** | Recommended best practice is to use a controlled. |
| **Examples** | `poricidal`, `longitudinal` |
| **Controlled vocabulary** | `longitudinal`, `poricidal`, `transverse`, `valvular` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
OK with this one.

**Comment by zedomel** [comment]
@fonturbel I also agree. We only need to define if we should use it with `dwc:Taxon or `dwc:Occurrence`.

I'm just wondering if `dwc:Taxon` represents a `group of of one or more populations of an organism or organisms seen by taxonomists to form a unit.`or if it represents just `a formal scientific name by which a group of organisms is known` (nomenclature). @pzermoglio ?

**Comment by pjbergamo** [comment]
Anther dehiscence is a very conserved trait and often used in plant taxonomy. I go for dwc:Taxon.

**Comment by carmensspires** [comment]
I have nothing to add.

**Comment by Andre-Luis-Acosta** [comment]
If relevant, can be added a new type: circumscissile dehiscence,[ R.V.Rethke ](https://doi.org/10.1002/j.1537-2197.1946.tb12926.x)

**Comment by cepnunes** [comment]
This looks fine to me.

**Comment by viniciusduartina** [comment]
This one is ok for me!

**Comment by joiceiamara** [comment]
I have nothing to add

**Comment by Mardiore** [comment]
I suggest deleting this part from the description: "...of the recorded plant species."

**Comment by anselmoeco** [comment]
It looks good to me.

**Comment by Andre-Luis-Acosta** [comment]
nothing to add from my side

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
**New definition**: `The physical mechanism of anther dehiscence (release of the pollen grains)`
