### ISSUE TITLE
apomiticSystem

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#39]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | apomiticSystem |
| **Definition** | The general mode of asexual reproduction through seeds of a plant species. |
| **Comments** | In absence or presence, but unknown, apomictic system the value should be filled according (`absence`, `unknown`) |
| **Examples** | `gametophytic`, `absent`, `unknown` |
| **Controlled vocabulary** | `present`, `absent`, `gametophytic`, `sporophytic`, `autonomous`, `pseudogamy`, `facultative`, `obligatory` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Any existing controlled vocabulary to be used here?

**Comment by fonturbel** [comment]
I don't feel qualified to comment on this entry.

**Comment by zedomel** [comment]
Same as in #57

**Comment by joiceiamara** [comment]
as @fonturbel I also don't feel qualified to comment on this entry.

**Comment by carmensspires** [comment]
I didn't understand what's in the item "Comments": In absence or presence, but unknown, apomictic system the value should be filled according.

**Comment by zedomel** [comment]
@carmensspires  I think that the idea is to emphasis that if you know that the plant has or not an apomitic system, but we don't know the specific system (`gametophytic`, `sporophytic`, etc.), then you should fill with `present` or `absent`. But I don't see differences between `present` and `unknown`. The first is saying that an apomitic system exists but it is unknown, and the second I think that is same, the apomitic system is `unkonwn` but `present`.

So, we can just use `present` and `absent`.

**Comment by viniciusduartina** [comment]
@zedomel, for apomictic systems, we should be able to use opposed values as gametophytic or sporophytic, autonomous or pseudogamous, facultative or obligate. Therefore, an individual plant could present an obligate autonomous sporphytic apomixis system, for example.

**Comment by zedomel** [comment]
@viniciusduartina , should we extend the controlled vocab or change the definition to match the cases you mention?

Cardoso et al, 2018 make a statement about it: 
> The classification of the apomictic systems presented in the next topics is based on: the embryo origin (1): gametophytic or sporophytic apomixis; the necessity of polar nuclei fertilization to endosperm development (2): autonomous apomixis or pseudogamy; and whether sexual and asexual reproduction occur concomitantly (3): facultative or obligate apomixis.

Based on that, do you think that is relevant to split this term in three terms:
- `apomiticSystemEmbryoOrigin`: **gametophytic** or **sporpophytic**
- `apomiticSystemFertilization`: **autonomous** or **pseudogamy**
- `apomiticSystemReproduction`: **facultative** or **obligate**

I'm suggesting it, because without a controlled vocab defining **all** possible combinations, machine interpretation will be compromised. For a machine `obligate autonomous sporophytic` is different from `autonomous obligate sporpophytic` (I don't know if it make sense). But what I'm trying to say is that the **order** of the classification elements (1, 2, and 3 in Cardoso et al, 2018) will make difference when filling this term.

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
We don't reach a consensus here yet.

**Comment by pietrokiyoshi** [comment]
I agree with the solution proposed by @zedomel to split in three (although it would be few plants for which we have this detailed data). So, would also keep a simple "present" or "absent" as well.

**Comment by RafaelCBorges** [comment]
I agree with @zedomel suggestion to split the term, thus for the species that this information is available it will be organized and machine readable, which will improve the long term usability of the data.

**Comment by pjbergamo** [comment]
Also agree with splitting the term. My doubt here is to species that are not apomitic. Maybe just add a comment stating that if the species is not apomitic, to not fill these terms?

**Comment by zedomel** [comment]
@pjbergamo  the main ideia is to people select those terms from the standard that they capable to fill based on their data. None of the terms are mandatory, so people should know that **ALL** term can be empty if they don't  have data. At the end, if someone has just the *plant name*, *animal name* and the *interaction type* the standard will accepted this data. 
But, we can add this to definition:
`The general mode of asexual reproduction through seeds of a` **`apomitic`** `plant species.`

Thus, this term will be split into *3* new terms.
**`apomiticSystemEmbryoOrigin`**: ` The general mode of apomixis embryo origin of a plant`
**`apomiticSystemFertilization`**: `The general mode of apomixis endosperm development of a plant`
**`apomiticSystemReproduction`**: `The general mode of apomixis reproduction of a plant`

Does anyone has any further suggestion on these new definitions? Any **Comments** to add?
