### ISSUE TITLE
antherPollenGrainsQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#4]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | antherPollenGrainsQuantity |
| **Definition** | The number of pollen grains (male gametophytes) found in the anther(s) of a flower. |
| **Comments** |  |
| **Examples** |  `1523`, `2641`, `1146` |
| **Controlled vocabulary** | |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** | General guidelines for filling fields: Pollen counting should be estimated in fresh or rehydrated pre-anthetic buds (flower almost opening) to prevent pollen grains loss after anthesis. Protocol 2.2. in Dafni et al. (2005); page 40-41. |

**Comment by zedomel** [comment]
The term definition:  `The number of pollen grains (male gametophytes) found in the anther(s) of a flower`, indicates that this is the number of pollen grains in the anthers of a particular flower of a particular plant. But I'm not sure can it be fitted in the data model. 

We can have many measurements of number of pollen grains for many flowers of a particular plant. Should this measurements be recorded for each flower (in a specific extension) or a summarised value for all flowers in a plant (e.g. average number of pollen grains)?

This seems to happen to other terms too. Sometimes they are related, sometimes not. Can we still use (E)MoF here? So, we will get multiple measurements for the same `measurementType' (i.e. `antherPollenGrainsQuantity`) with different `measurmentID`. 

This term is not strictly related to the Interaction, as the number of pollen grains in anther(s) is a trait of a particular plant and do not have anything related to the Interaction (an interaction could or could not be recorded, and this can be measured in the same way). 

Particularly, I don't like the ideia of a term represent an "average" value, as this a secondary data, and not raw data. But what we can do here? Multiple `antherPollenGrainsQuantity` records in (E)MoF extension linked to a particular `dwc:Occurrence`?

**Comment by fonturbel** [comment]
No comments on this term

**Comment by zedomel** [comment]
**New definition**: `The total number of pollen grains in the anther(s) of a flower.`
