### ISSUE TITLE
availableFlowerQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#40]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | availableFlowerQuantity |
| **Definition** | The number or enumeration value for the quantity of open flowers or inflorescences available to visitors. |
| **Comments** |  |
| **Examples** | `0`, `30`, `40` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Change term definition: 
`The quantity of open flowers or inflorescences available to floral visitors`

Do we really need the **available to floral visitors** in the term definition? How can an open flower not be available?

**Comment by fonturbel** [comment]
Indeed, this term could be simply called "flowerQuantity"

**Comment by Andre-Luis-Acosta** [comment]
About the quotation "How can an open flower not be available?" The term OPEN (potentially) suggest availability.. but, pre anthesis flowers are present in plant also, mas não estão available, except for bees like Bombus, that can make a hole in corolla base and extract the pollen of closed flowers, but this is looting (negative interaction for plant).

**Comment by Andre-Luis-Acosta** [comment]
About the quote "How can an open flower not be available?" The term OPEN (potentially) suggests availability .. but, pre-anthesis flowers are present in the plant as well, but they are not available, except for bees like Bombus, which can make a hole at the base of the corolla and extract pollen from closed flowers, but this is stealing (negative interaction for plant).  OpenFlowerQuantity?

**Comment by zedomel** [comment]
@Andre-Luis-Acosta  so, we just have to change the definition to avoid ambiguity on the meaning of **`available`**. Maybe the definition can be simple like: `The quantity of open flowers or inflorescences of an individual plant`, so does not matter if it is **available** or not, since it is open it is *potentially* available (?)

Sounds better?

**Comment by carmensspires** [comment]
What do we mean by availableFlowerQuantity? Flowers available to floral visitors? That is, flowers that are open and offering some kind of resource. But, an open flower can be a less attractive flower or even unattractive for the floral visitor. Flowers that have already been pollinated and remain open are less attractive and are available.

I don't see much sense in this label. I think this measure only makes sense if it is associated with the age of the flower and the fact that it is pollinated or not.

When we measure flowers available to pollinators, we count only flowers open on the day of sampling, that is, flowers that will still be visited on that specific day. And the measurements are made depending on the flower's phenology.

But, I leave the decision to the experts in floral biology ....

**Comment by zedomel** [comment]
@carmensspires your comment shows how ambiguity this term is. We have to define what we mean by **available**. 

Regarding to the associated terms (age of the flower and if it is pollinated or not) I'm not sure how difficult can be to measured that, specially if a flower was pollinated or not. Let's see what other have to say.

The new definition that I proposed in my [previous comment](https://github.com/BioComp-USP/rebipp-data-standard/issues/40#issuecomment-760306953) sounds more like `flowerAbundance`: **the number of open flowers of an individual**. But it may be expressing a different concept compared to the original one (**available to floral visitors**).

**Comment by cepnunes** [comment]
Nothing to add.

**Comment by pjbergamo** [comment]
It is quite impossible to know the age of all flowers or if they were pollinated when one is counting the number of flowers. 
I see that the problematic word here is 'available'. Therefore, I agree with @zedomel new definition.

**Comment by viniciusduartina** [comment]
Agree with the new definition. I think we don´t need "available to floral visitors" as well.

**Comment by carmensspires** [comment]
@zedomel I agree with thew term #flowerAbundance  and definition:  the number of open flowers of an individual.

**Comment by anselmoeco** [comment]
I agree with the new term and definition proposed by @zedomel, much better!

**Comment by Andre-Luis-Acosta** [comment]
@zedomel agree with you on flowerAbundance term

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
**New label**: `flowerAbundance`
**New definition**:  `The number of open flowers of an plant individual`
