### ISSUE TITLE
floralAdvertisement

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#42]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | floralAdvertisement |
| **Definition** | A list (concatenated and separated) of structures and substances that function advertising the flowers (and its rewards) to floral visitors. Usually as visual, olfactory and tactile stimuli. |
| **Comments** | Term reference (literature): Willmer et al. 2011 |
| **Examples** |  |
| **Controlled vocabulary** | colored structure; presence of perfume (diurnal); presence of perfume (nocturnal); presence of osmophores |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Controlled vocabulary should be simpler and give the details in the examples.

**Comment by zedomel** [comment]
Change **Comments** to:  `Recommended best practice is to adopt a controlled vocabulary`.

Change term **Label** to: **`floralAttractants`**

Change **Definition** to: `A list (concatenated and separated)  of visual and chemical cues used by animals to locate flowers and the rewards that they offer, in order to increase the probability of floral visitation.`

Also, this property appears to be more related to the visiting animal than to the plant. A flower structure or substance can be an attractant to one animal species but not to another species. Additionally, it can be an attractant to one sex but not to other (e.g. orchids that mimic the pheromones of wasps females to attract males). So, should we move this term to the `Animal` class, and change definition according? Example:  `A list (concatenated and separated)  of visual and chemical cues used by the` **`animal species`** `to locate flowers and the rewards that they offer`

**Comment by pietrokiyoshi** [comment]
A good point that "attractiveness" will change according to the animal. However, not sure about moving to class animal, as these properties are still located in the flowers/plants.

**Comment by zedomel** [comment]
@pietrokiyoshi  perhaps we can move it to the `Interaction` class. The **attractiveness** is dependent of **the animal species**, as well as, **the plant species**. From the side of the animal does not make sense to say that it is attracted by the `flower fragrance` if the `Interaction` was recorded with a plant species that does not produces any fragrance. 

Moving it to the `Interaction` class and change the definition accordingly could fix this problem. I'm not sure. The problem of moving it to the `Interaction` is that the term will be related specially to recorded interaction, in other words, it will need an evidence for that. Because, the interpretation will be `for this specific Interaction: the animal was attracted by the flower fragrance of the plant`. But to saying that the person who collect/produce the data need to have an evidence that support this statement.

Let's hear from other what they think.

**Comment by carmensspires** [comment]
I agree with zedomel proposal of moving it to Interaction, since this type of floral characteristic is only studied within the context of floral plant-visitor interaction.

**Comment by pjbergamo** [comment]
I am not completely sure about moving this one to Animal or Interaction classes.

First, as @pietrokiyoshi said, the attractant is on the plant.
Second, the problem I see in moving to Interaction class is to attach floral attractants to a specific interaction (in other words, to a specific visitor species). This because the only way to be completely sure that a structure/fragrance/etc functions to attract a specific visitor is through detailed experiments. This will impose a very specific requirement to fill this term, making it quite useless.

With these issues in mind, I suggest to keep this term in the plant class and change the defenition to:

A list (concatenated and separated) of **all** visual, chemical and tactile cues **present in the flowers** that floral visitors **may use** to locate flowers and their rewards

**Comment by carmensspires** [comment]
I agree with @pjbergamo to keep this term in the plant class and I also agree with the new definition proposed by him.

**Comment by zedomel** [comment]
@pjbergamo  very good arguments. I just have a few suggestion to the definition you proposed:

`A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their rewards`

Just removed the **all** word from the definition, as it suggest that the term should be filled with **ALL** attractants, but it's possible that people don't known which are all the attractants, opposed to some of them.

**Comment by zedomel** [comment]
@pjbergamo  so, are you saying that the term `attractiveStructure` #8  is useless? 
>This because the only way to be completely sure that a structure/fragrance/etc functions to attract a specific visitor is through detailed experiments.

Since, we already have a term for visual attractants `attractiveStructure` that is related to the `Interaction`, I was just suggesting to do the same here and simplify things. Maybe, moving this term to the `Interaction`, then all the terms related to the attractants can be merged in just one term (simplifying the standard).

Without an empiric evidence of which structures/fragrance/etc functions as attractants, this term will be filled just with assumptions? 

I understand that the term can be filled with structures/fragrances/etc that are known in the literature to act as attractants for particular animal species, even the animal species in the `Interaction` being reported is not one of the species found in the literature. But it sounds strange to me, and I will try to explain with an example.

The way it is now (a `Plant` term) it can be filled as follow:

| occurrenceID | measurementID | measurementType | measurementValue|
|----:|----:|-----:|----:|
| 1 | 1 | `floralAdvertisement`| `colored structure \| presence of perfume (diurnal)`|
| 2 | 2 |`floralAdvertisement`| `colored structure`|

So, we know from the dataset above that the plant species of occurrence `1` has `colored structure | presence of perfume (diurnal)` as `floralAdvertisement` and occurrence `2` just `colored structure`

But, for example, for a particular interaction of an `Animal` (a bat, which are attracted by flowers vexillum reflectance of ultrasonic emissions) with the occurrence `1` we can also have for the term `attractiveStructure`:

| interactionID | measurementID | measurementType | measurementValue|
|----:|----:|-----:|----:|
| 1 | 1 | `attractiveStructure`| ` vexillum`|

So, the `attractiveStructure` could not be in the set of `floralAdvertisement` reported in the same dataset or even in different datasets. It should be include or not? 

On other hand, with a requirement of an empirical evidence for a structure acting as attractant, we can **remove** this term from the standard and use `attractiveStructure`. As example assume three **interactions** between different animal species and the same plant species. Then we will have something like:

| interactionID | measurementID | measurementType | measurementValue|
|----:|----:|-----:|----:|
| 1 | 1 | `attractiveStructure`| ` vexillum`|
| 2 | 2 | `attractiveStructure`| `petal`|
| 3 | 3|  `attractiveStructure`| `perfume (diurnal)`|

From this dataset we can infer that `vexillum`, `petal` and `perfume (diurnal)` are some of the structures used as `floralAdvertisement`, so we don't need a term form `floralAdvertisement` in that case. When looking to **all** data in a **database** for `attractiveStructure` we could infer the all the known floral (and possible non-floral) structures acting as attractants, aggregating it by plant species, animal species or both.

Let me know, if I'm missing something here. But I'm just trying to simplify the standard as much as possible. Some quotes from DwC paper:
>The philosophy for Darwin Core development has been to keep the standard as simple and open as possible and to develop terms only when there is shared demand

>The simplicity and flexibility of Darwin Core has made it possible for REBIOMA to provide immediate access to high-quality data and tools for monitoring and assessing conservation efforts

**Comment by pjbergamo** [comment]
Let's go back to the rationale behind these three terms:

floralAdvertisement was created to list all potential attractants in a flower that may function as advertisement to flower visitors. These include color, fragrance, tactile stimuli, sound, and so on.
In my view, this should contemplate all cases listed above by @zedomel 

However, we also know that from all attractants, color is by far the most studied and most easily recorded. Plant trait databases (e.g. TRY database, BioFlor, and others) often include flower color because it is very easy to classify and obtain this trait in comparison with fragrance (I am not delving in the issue of human vs. insect vision here because this will complicate the database).

This is why two new terms specific for color were created:
One to specifically state which color is (attractiveStructureColor). In other words, this is would be equivalent to "flower color" often found in plant trait databases. 
The second was created due to the cases on which petals are not the colored structure. In this cases, bracts, sepals or modified anthers can be the colored structure and thus, the color of this structure that is important to define "flower color".

**Comment by pjbergamo** [comment]
My suggestion is to reduce these three terms to two:

We could expand floralAdvertisement to include all possible colored attractive structures / substances:
colored petal, colored sepal, colored stamen, colored pistil, colored bract, fragrances (diurnal), fragrances (nocturnal), osmophores, tactile stimuli, sonic stimuli

And a second one specific to state the color (attractiveStructureColor or renamed to flowerColor to simplify).

**Comment by cepnunes** [comment]
Nothing to add to this rich discussion!

**Comment by zedomel** [comment]
@pjbergamo  following the discussion on #29, should we add **potential** to the definition:

<pre>A list (concatenated and separated) of <b>potential</b> structures and substances that function advertising the flowers and its <b>resources</b> to floral visitors.</pre>
**Comments**: `Usually as visual, olfactory and tactile stimuli``

Another thing here is: do we need to specify values like `colored petal` or we can just say `petal` since the definition of the term is to list the structures and not the characteristics of the structures? Could you give examples other than `colored` ?

**Comment by pjbergamo** [comment]
@zedomel I would say that is important to qualify the structures somehow to avoid confusion with filling the term due to the mere presence of the structure. For example, a flower have pistils but they have no apparent function as attractant.

**Comment by paf1306** [comment]
I agree with @pjbergamo and to @zedomel definition "A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their rewards"

**Comment by zedomel** [comment]
**New label**: `floralAttractants `
**New definition**: `A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their resources`
**Comments**: `Recommended best practice is to separate the values (singular) in a list with space vertical bar space ( | )`

For visual attractants this term sounds that is overlapping with the term `attractiveStructure` (#8). Can we get rid of the term `attractiveStrcuture` (#8) and adopt this one with values like `colored petals`, `colored sepals` etc.? If so, we should change the term `attractiveStructureColor` (#29) label to  `flowerColor` and the definition would be : `The predominant color of the flower`.

It would change the interpretation of `attractiveStructureColor` (`The predominant color of the flower's structure which act as a visual attractant`) since a flower can have for example two colors (`red` and `yellow`) and the predominant color of a flower is `yellow` but the color which attracts the visitor  is `red`. So, the `flowerColor` definition is not the same as `attractiveStructureColor`.  However, based on other discussions, in order to have certain that a flower's structure and its colors really acts as attractant to a visitor may require specific experiments. So, the definition of `flowerColor` sounds more general and do not make any assumptions about the preference of the visitors (it should be inferred after, analyzing  the whole database for visitor species and flower color and looking for most common patterns of preferences).

**Comment by fonturbel** [comment]
> **New label**: `floralAttractants `
> **New definition**: `A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their resources`
> **Comments**: `Recommended best practice is to separate the values (singular) in a list with space vertical bar space ( | )`
> 
> For visual attractants this term sounds that is overlapping with the term `attractiveStructure` (#8). Can we get rid of the term `attractiveStrcuture` (#8) and adopt this one with values like `colored petals`, `colored sepals` etc.? If so, we should change the term `attractiveStructureColor` (#29) label to `flowerColor` and the definition would be : `The predominant color of the flower`.
> 
> It would change the interpretation of `attractiveStructureColor` (`The predominant color of the flower's structure which act as a visual attractant`) since a flower can have for example two colors (`red` and `yellow`) and the predominant color of a flower is `yellow` but the color which attracts the visitor is `red`. So, the `flowerColor` definition is not the same as `attractiveStructureColor`. However, based on other discussions, in order to have certain that a flower's structure and its colors really acts as attractant to a visitor may require specific experiments. So, the definition of `flowerColor` sounds more general and do not make any assumptions about the preference of the visitors (it should be inferred after, analyzing the whole database for visitor species and flower color and looking for most common patterns of preferences).

This new proposal makes more sense... a given plant may have more than one attractive structure, but I am not convinced to include the color in here, just the structure type.

**Comment by RafaelCBorges** [comment]
> **New label**: `floralAttractants `
> **New definition**: `A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their resources`
> **Comments**: `Recommended best practice is to separate the values (singular) in a list with space vertical bar space ( | )`
> 
> For visual attractants this term sounds that is overlapping with the term `attractiveStructure` (#8). Can we get rid of the term `attractiveStrcuture` (#8) and adopt this one with values like `colored petals`, `colored sepals` etc.? If so, we should change the term `attractiveStructureColor` (#29) label to `flowerColor` and the definition would be : `The predominant color of the flower`.
> 
> It would change the interpretation of `attractiveStructureColor` (`The predominant color of the flower's structure which act as a visual attractant`) since a flower can have for example two colors (`red` and `yellow`) and the predominant color of a flower is `yellow` but the color which attracts the visitor is `red`. So, the `flowerColor` definition is not the same as `attractiveStructureColor`. However, based on other discussions, in order to have certain that a flower's structure and its colors really acts as attractant to a visitor may require specific experiments. So, the definition of `flowerColor` sounds more general and do not make any assumptions about the preference of the visitors (it should be inferred after, analyzing the whole database for visitor species and flower color and looking for most common patterns of preferences).

@zedomel, thus this term will be related to attractive structures of plants only, but not to colors? 
If that is the case, I think this proposal is good and encompass the required inputs for further usability, as the colors will be in another field. 
After the discussion above, I believe it would be interesting to ask for the method for obtaining the information on chemical attractants. So, if an input says that the flower has chemical attractants, they also provide how this information was obtained.

**Comment by pjbergamo** [comment]
I agree with @zedomel's proposal.

**Comment by zedomel** [comment]
@RafaelCBorges the proposal is to removed the term `attractiveStructure` since the **attractiveness** if a species dependent characteristics, an som it may change from one species to another. Due the problems expressed here about the difficult in have specific experiments to determine which really acts as attractants for specific visitor species. Then, the proposal was made to remove the term `attractiveStructure` and maintain only this term `floralAdvertisement` with the new label and definition:

**New label**:  `floralAttractants`
**New definition**: `A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their resources`

So, this new definition encompasses all kinds of cues (*visual*, *chemical* and *tactile*, are we missing any other?) and does not make any assumption about the **attractiveness** of this cues as it says **`may use to locate`**.

Can I close this issue?

**Comment by RafaelCBorges** [comment]
Yes @zedomel, agree and all clear from my side.

**Comment by zedomel** [comment]
> **New label**: `floralAttractants `
> **New definition**: `A list (concatenated and separated) of visual, chemical and tactile cues present in the flowers that floral visitors may use to locate flowers and their resources`
> **Comments**: `Recommended best practice is to separate the values (singular) in a list with space vertical bar space ( | )`
> 
> For visual attractants this term sounds that is overlapping with the term `attractiveStructure` (#8). Can we get rid of the term `attractiveStrcuture` (#8) and adopt this one with values like `colored petals`, `colored sepals` etc.? If so, we should change the term `attractiveStructureColor` (#29) label to `flowerColor` and the definition would be : `The predominant color of the flower`.
> 
> It would change the interpretation of `attractiveStructureColor` (`The predominant color of the flower's structure which act as a visual attractant`) since a flower can have for example two colors (`red` and `yellow`) and the predominant color of a flower is `yellow` but the color which attracts the visitor is `red`. So, the `flowerColor` definition is not the same as `attractiveStructureColor`. However, based on other discussions, in order to have certain that a flower's structure and its colors really acts as attractant to a visitor may require specific experiments. So, the definition of `flowerColor` sounds more general and do not make any assumptions about the preference of the visitors (it should be inferred after, analyzing the whole database for visitor species and flower color and looking for most common patterns of preferences).

Closed
