### ISSUE TITLE
floralReward

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#43]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | floralReward |
| **Definition** | A list (concatenated and separated) of rewards offered by flowers to visiting animals in order to award their services. |
| **Comments** | Absence of reward applies when flowers are pollinated by deceit (no reward offered to visiting animals). Recommended best practice is to separate the values in a list with space vertical bar space ( `\|` ) and use a controlled vocabulary of floral rewards. |
| **Examples** | `nectar`, `pollen \| nectar`, `absence of reward` |
| **Controlled vocabulary** | `nectar`, `pollen`, `oil`, `gum`, `resin`, `perfume`, `floral tissues`, `other`, `absence of reward` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Instead of "absence of reward" I suggest using just "absent".

**Comment by zedomel** [comment]
@fonturbel  I agree. 

I just have comment about the definition. The sentence **rewards offered by flowers to visiting animals in order to award their services**, makes explicit that the visiting animal is providing a service to the plant, but it can not be always the case (e.g. theft, robbing), and the reward is still there. The **reward** concept only makes sense when the visiting animal is a **true** pollinator. A different definition may be: `any structure or secretion of the flower that can be gathered or consumed by pollinators`. 

Are there cases where **services** does not mean **pollination**?

Also maybe we should make distinct the **floral rewards** from the **floral attractants** (#42)

**Comment by pietrokiyoshi** [comment]
I would change to "no reward".
I can see you point @zedomel, and agree with your alternative: "any structure or secretion of the flower that can be gathered or consumed by pollinators" 
A service for plants in this case would be pollination.

**Comment by joiceiamara** [comment]
I agree with @zedomel and @fonturbel

**Comment by carmensspires** [comment]
I agree with @zedomel and @fonturbel, but I suggest tochange "pollinators" for flower visitors", since not all flower visitors will be a true pollinator, but amost all flower visitor will collect some thing in the flower.

Any structure or secretion of the flower that can be gathered or consumed by flower visitors.

**Comment by pjbergamo** [comment]
I agree with @fonturbel @zedomel and @carmensspires. In most definitions, "flower visitors" will be preferable in comparison with "pollinators".

**Comment by cepnunes** [comment]
The use of the term Reward to designate the resources collected by floral visitors and pollinators is controverse, while the use of the more general term, Resource, is less controverse as it does not imply in assuming and intentionality to both plants and pollinators.

Thus, I agree that this term should be merged to the floralReward term, with a definition slightly different of both current definitions: "A list (concatenated and separated) of floral resources collected an animal visitor or pollinator from a flower during an Interaction."

Additionally, it is important to have in mind which term related to the Animal would differentiate it into pollinator or non-pollinating floral visitor.

**Comment by Mardiore** [comment]
In my opinion the definition is correct.

**Comment by paf1306** [comment]
I endorse @pjbergamo comment.

**Comment by zedomel** [comment]
**New definition**:  `Any structure or secretion of the flower that can be gathered or consumed by flower visitors`
**Controlled vocabulary**:  `nectar`, `pollen`, `oil`, `gum`, `resin`, `perfume`, `floral tissues`, `other`, `absent`
