### ISSUE TITLE
floralSymmetry

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#44]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | floralSymmetry |
| **Definition** | The symmetry describing whether, and how, a flower, in particular its perianth, can be divided into two or more identical or mirror-image parts. |
| **Comments** | There are essentially two main types of symmetry in flowers: bilateral symmetry (also termed zygomorphic, dorsiventral, lateral or irregular) and radial symmetry (also termed actinomorphic or regular). Recommended best practice is to use a controlled vocabulary such as  Phenotype and Ant Trait Ontology (PATO) |
| **Examples** | `zygomorphic`, [`http://purl.obolibrary.org/obo/PATO_0001327`](http://purl.obolibrary.org/obo/PATO_0001327) |
| **Controlled vocabulary** | [Phenotype And Trait Ontology](http://purl.obolibrary.org/obo/PATO_0000965) |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Controlled vocabulary: zygomorphic; actinomorphic.

**Comment by zedomel** [comment]
@fonturbel  I think that [Phenotype And Trait Ontolgy](http://purl.obolibrary.org/obo/PATO_0000965) covers all the use cases.

**Species trait** as in #57 ?

**Comment by viniciusduartina** [comment]
Agree with the use of Phenotype And Trait Ontolgy as reference.

**Comment by carmensspires** [comment]
I have nothing to add.

**Comment by cepnunes** [comment]
I have nothing to add.

**Comment by Mardiore** [comment]
If possible, I also suggest the use of http://www.ibiblio.org/botnet/glossary/ as reference. This glossary is based in Radford et al. (1976) and has illustrations.

**Comment by anselmoeco** [comment]
It is important to consider asymmetric flowers here.

**Comment by paf1306** [comment]
Nothing to add

**Comment by zedomel** [comment]
> If possible, I also suggest the use of http://www.ibiblio.org/botnet/glossary/ as reference. This glossary is based in Radford et al. (1976) and has illustrations.

@Mardiore  thank you for sharing this glossary. We can fully or partially adopt it. The controlled vocabulary is not part of the standard. So people can adopt any controlled vocab they like or even create their own vocab. But, internally REBIPP should define controlled vocabs. as a suggestion for people to use.

**Comment by zedomel** [comment]
Controlled vocab defined.
