### ISSUE TITLE
floralSystem

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#45]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | floralSystem |
| **Definition** | The floral system (morphological, temporal or movement-based mechanism) in which bisexual flowers optimize their reproductive success, through mechanisms that promote self- or cross-pollination. |
| **Comments** |  |
| **Examples** | `herkogamy`, `heterostyly`, `stylar dimorphism` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
The controlled vocabulary is missing. This should be consulted to a specialist to cover the full range of options.

**Comment by viniciusduartina** [comment]
You may use Cardoso et al. 2018 as a reference for the Floral Systems.

**Comment by carmensspires** [comment]
I don't feel able to contribute.

**Comment by cepnunes** [comment]
I have just a minor suggestion of change to the definition of this term. I could be: The system by which bisexual flowers optimize their reproductive success, through mechanisms that promote self- or cross-pollination. It can be a morphological, temporal or movement-based mechanism". 

I also agree with all previous comments.

**Comment by zedomel** [comment]
@carmensspires  I agree with some minor changes :-D
**Definition**:  `The system by which bisexual flowers optimize their reproductive success, through mechanisms that promote self- or cross-pollination`
**Comments**: `It can be a morphological, temporal or movement-based mechanism".`

**Comment by viniciusduartina** [comment]
Maybe include more examples as: heteranthery, enantiostily, dichogamy, flexistily, heterodichogamy, etc

**Comment by paf1306** [comment]
Nothing to add

**Comment by zedomel** [comment]
**New definition**: `The system by which bisexual flowers optimize their reproductive success, through mechanisms that promote self- or cross-pollination`
**Comments**: `It can be a morphological, temporal or movement-based mechanism`
**Controlled vocabulary**:  adopt Cardoso et al. 2018 terms
