### ISSUE TITLE
flowerShape

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#46]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | florwerShape |
| **Definition** | The overall shape of the flowers. |
| **Comments** | Recommended best practice is to use a controlled vocabulary. |
| **Examples** | `bush`, `campanulate`, `tube` |
| **Controlled vocabulary** | `brush`; `campanulate`; `bell-shaped`; `lantern`; `trumpet-shaped`; `open disk` (`bowl`); `spherical`; `tube`; `keel`; `iris-type flower`, `orchid flowers`; `composite`; `trap` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
I agree with the term, no further comments.

**Comment by zedomel** [comment]
Here we need definitions for each term in controlled vocab (e.g. `bush`, `campanulate`, etc)

**Comment by viniciusduartina** [comment]
Maybe you can use cap. 10 of Faegri and Pijl 1979 to define the values of this term.

**Comment by pietrokiyoshi** [comment]
The terms seem to be the usual ones used in the literature (although it may be difficult sometimes to classify the flowers to a specific category)

**Comment by zedomel** [comment]
@viniciusduartina  could you share this chapter with me? I don't have access to this book :-(

@pietrokiyoshi can we simplify the controlled vocab to covers only more general cases?

**Comment by joiceiamara** [comment]
Nothing to add

**Comment by carmensspires** [comment]
Nothing to add

**Comment by carmensspires** [comment]
Nothing to add

**Comment by cepnunes** [comment]
Agree with the comments above. No further comments.

**Comment by Mardiore** [comment]
Salim, I also suggest consulting http://www.ibiblio.org/botnet/glossary// (D. Perianth and Hypanthium Structural Types (Figure 6-6-2))

**Comment by Mardiore** [comment]
@zedomel, if you have not yet received access, I send you the PDF of the book mentioned by @viniciusduartina 
[Principles of Pollinaiton Ecology -  Faegri & Van Der Pijl 1979.pdf](https://github.com/BioComp-USP/rebipp-data-standard/files/6061981/Principles.of.Pollinaiton.Ecology.-.Faegri.Van.Der.Pijl.1979.pdf)

**Comment by anselmoeco** [comment]
> Here we need definitions for each term in controlled vocab (e.g. `bush`, `campanulate`, etc)

I think we can use the 12 types and definitions in Patt Willmer's book that incorporate the classification proposed by Faegri & Van Der Pijl.

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
For the controlled vocab we will adopt Patt Willmer's book and Faegri & Van Der Pijl.
