### ISSUE TITLE
flowerHabit

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#47]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | flowerHabit |
| **Definition** | The position (in relation to the ground) the open flower is presented to flower visitors. |
| **Comments** | Term reference (literature): Faegri and van der Pijl (1979); Willmer (2011); Rech et al. (2014). |
| **Examples** | `pendent`, `declined` |
| **Controlled vocabulary** | `pendent`; `erect`; `declined`; |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
No further comments!

**Comment by zedomel** [comment]
One comment that @pzermoglio shared to me is related to the **flower visitors** in the definition. What do we mean with **flower visitors**? It should be defined somewhere, even it is clear to us. Or we should change the definition to remove the sentence **flower visitors** and adopt a definition that does not depending on ecological or functional aspects.

I also suggest to change the term label to: **`floralOrientation`**

And the definition could be something like:  `the angle between a flower’s main axis and the horizontal *plane*` [Wang et al. 2014](https://doi.org/10.1371/journal.pone.0095381). Can we change this definition to make explicit the use of discrete "angles" like `pendant`, 'declined`?

[Neal et al. 1998](https://www.jstor.org/stable/221712) make a statement about it: 

> [...] developmental or morphological aspects of symmetry (i.e. orientation in relation to growth of the plant) to be evaluated separately from the ecological or functional aspects of symmetry (i.e. orientation in the pollination process)

Also, I think we should change **Comments** to: `Recommended best practice is to use a controlled vocabulary`.

**Comment by viniciusduartina** [comment]
I agree that #floralOrientation is a better term.

**Comment by pietrokiyoshi** [comment]
I agree to change to floralOrientation

**Comment by joiceiamara** [comment]
I also agree to change to floralOrientation and with its definition.

**Comment by arech2003** [comment]
Yes, flower orientation is better. We can get rid of flower visitors and the meaning does not change. I will not move to angles and plane surfaces as it increase complexity...

**Comment by zedomel** [comment]
@joiceiamara  and @arech2003  what do you think of changing the defiinition to:

**flowerOrientation**:  `the orientation between a flower’s main axis and the horizontal plane`

Sounds better?

**Comment by joiceiamara** [comment]
@zedomel yes, it sounds much better

**Comment by carmensspires** [comment]
I agree that the term orientation is better than habit. But, I still couldn't understand how to choose between the options: pendent; erect; declined, taking into account the floral visitor. A flower has different floral visitors with different habits.

I am trying to think of different examples of flower position and different floral visitors to see how I would fill this item: Example 1: a flower with the opening oriented upwards in relation to the soil and a floral visitor who arrives at the flower walking through the stem until it reaches the flower inside; Example 2: a flower with the opening oriented upwards in relation to the soil and a floral visitor who arrives at the flower flying over it and lands on the petal.

I think this label is not making much sense ...

**Comment by joiceiamara** [comment]
I agree with @carmensspires and, because of that, I believe that the defintion should not consider the floral visitor, like the definition proposed by @zedomel: 

flowerOrientation: the orientation between a flower’s main axis and the horizontal plane

I belive that this simplifies the definition, otherwise I it does not make sense to me either

**Comment by cepnunes** [comment]
Agree with the new name for the term.

**Comment by Mardiore** [comment]
floralOrientation is much better.

**Comment by anselmoeco** [comment]
I agree with the new term and definition summarized in the last post of @joiceiamara !

**Comment by cepnunes** [comment]
I endorse the agreement with @joiceiamara

**Comment by paf1306** [comment]
I also endorse the agreement with @joiceiamara.

**Comment by zedomel** [comment]
**New label**: `flowerOrientation`
**New definition**: `the orientation between a flower’s main axis and the horizontal plane`
**Comments**: `Recommended best practice is to use a controlled vocabulary of flower orientation`
