### ISSUE TITLE
flowerLongevity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#48]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | flowerLongevity |
| **Definition** | The total period of time in hours comprising the time between flower opening and flower senescence (when floral parts begin to wilt and fall off or the ovary starts to develop into fruit). |
| **Comments** | Specify the period of time (options with a period varying from 1h to 72h, number of days or weeks). |
| **Examples** | `1`, `8`, `72`, `120` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Change term definition: `The total period of time in hours comprising the time between flower opening and flower senescence`.

Is it the longevity of a particular flower, measured by a collector or an average/literature longevity?
Can we have multiple **flower longevity** measures of the flowers of an individual plant or multiple plants?

**Comment by fonturbel** [comment]
OK, but it should be standardized to days in order to avoid mixing days and weeks (or you'll need another field specifiyng time unit, making it unnecesarily messy)

**Comment by viniciusduartina** [comment]
@zedomel you can find this measurement associated to an specific flower and also to the species in the literature.

**Comment by pietrokiyoshi** [comment]
I would suggest standardizing to hours. Usually measured for each flower in the field or for an individual plant. Is it possible to specify the unit of measurement?

**Comment by zedomel** [comment]
The definition already makes explicit the unit of measurement (**hours**). But, we can use [`dwc:MeasurementOrFact`](http://rs.tdwg.org/dwc/terms/MeasurementOrFact) which defines the terms:

- [`dwc:measurementType`](http://rs.tdwg.org/dwc/terms/measurementType)
- [`dwc:measurementValue`](http://rs.tdwg.org/dwc/terms/measurementValue)
- [`dwc:measurementUnit`](http://rs.tdwg.org/dwc/terms/measurementUnit)

It will make thingss a lit bit complicated, because instead of filling one field, it will require filling at least three fields. But, following what I have said on another [issue](https://github.com/BioComp-USP/rebipp-data-standard/issues/10#issuecomment-758850135), the way we are modeling the standard some terms will be represented using `dwc:MeasurementOrFact`. If this is the case for this term, then we should remove the **unit of measurement** from the definition and use `dwc:measurementUnit` for that:
`The total period of time comprising the time between flower opening and flower senescence (when floral parts begin to wilt and fall off or the ovary starts to develop into fruit).`

I will try to explain with an example how complicated can be not setting the **unit of measurement** in the definition.
The idea of define the term `flowerLongevity` with a defined **unit of measurement** is to abstract the use of `dwc:MeasurementOrFact` (make it simpler):

| occurrenceID | flowerLongevity |
|------:|------:|
| occ 1 | 2 |
| occ 1 | 24 |
| occ 2| 48 |

will be *translated* to:

| occurrence ID | measurementID | measurementType | measurementValue | measurementUnit|
|-----:|-----:|-----:|-----:|-----:|
| occ 1| meas 1 | `flowerLongevity`| 2 | hours |
| occ 1| meas 2 | `flowerLongevity`| 24 | hours|
| occ 2| meas 3 | `flowerLongevity`| 48 | hours|

If we decide to **remove** the **unit of measurement** from the definition, then we will need a new term to specify the **unit**:
| occurrenceID | flowerLongevity |flowerLongevityUnit|
|------:|------:|-----:|
| occ 1 | 2 | days|
| occ 1 | 24 | hours|
| occ 2| 48 | hours|

**OR** request people to use `dwc:MeasurementOrFact`directly:

| occurrence ID | measurementID | measurementType | measurementValue | measurementUnit|
|-----:|-----:|-----:|-----:|-----:|
| occ 1| meas 1 | `flowerLongevity`| 2 | days |
| occ 1| meas 2 | `flowerLongevity`| 24 | hours|
| occ 2| meas 3 | `flowerLongevity`| 48 | hours|



So, will be much simpler if we set the **unit of measurement* in the definition, and for a better understand we can change the label to: **`flowerLongevityInHours`**

**Comment by arech2003** [comment]
Definetely I go for hours and avoid this unit definition issues. This should be a measure for one individual flower or for the individual but not for the species. I feel the need to defferentiate this term from FunctionalFlowerLifespan in the definition as this will be a common misconfusion.

**Comment by zedomel** [comment]
@arech2003  good. Do you have any suggestion in how we should differentiate this term from `functionalFlowerLifespan` to avoid confusion?

Regarding to `funcionalFlowerLifespan` (#51) I would suggest to change the definition.

Here we should make explicit that the term related to **one individual flower** or **flowers of an individual plant**, but not both. So, we need a consensus if the term will **be for each flower** (one value for each measured flower) or **for each plant** (average value for the individual). Suggestions? 

Can someone provide examples of datasets?

**Comment by carmensspires** [comment]
These values of flower longevity (in hours, in days ...) can vary between flowers of the same plant. So, we must set these values for a flower individually.

**Comment by pjbergamo** [comment]
Yes, flower longevity can vary between flowers of the same plant but I would say that such variation is quite small for most plant species. Usually, flower longevity is treated as a population trait, and most studies present data as an average (in the best cases, a range) across flowers in a population (one seminal example is Ashman & Schoen 1994 Nature).
I am not aware of any study that have measured flower longevity for each flower involved in an interaction with pollinators, so I go for setting it as an average for the individual.

Suggestion of new definition to avoid confusion with functionalFlowerLifespan:
The average total period of time in hours comprising the time between flower opening (petals fully open regardless of anther maturation and stigma receptivity) and flower senescence (when floral parts begin to wilt and fall off or the ovary starts to develop into fruit) of a plant individual.

**Comment by cepnunes** [comment]
Nothing to add.

**Comment by Mardiore** [comment]
I agree with Pedro, but I don't think it's necessary to change the definition here, because both definitions(flowerLongevity AND  functionalFlowerLifespan) are different, I don't think it's confusing.

**Comment by anselmoeco** [comment]
I agree with @pjbergamo and @Mardiore!

**Comment by paf1306** [comment]
I agree with @pjbergamo definition. Nothing else to add.

**Comment by zedomel** [comment]
**New definition**:  `The total period of time in hours comprising the time between flower opening and flower senescence`
**Comments**:  `A flower is considered opened when its petals are fully open regardless of anther maturation and stigma receptivity, and flower senescence is when floral parts begin to wilt and fall off or the ovary starts to develop into fruit`.
