### ISSUE TITLE
flowerOpeningPeriod

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#49]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | flowerOpeningPeriod |
| **Definition** | The period of the day which a sample of chasmogamous flowers' buds open their corolla, exposing the reproductive parts to flower visitors. |
| **Comments** | Recommended best practice is to use a controlled vocabulary of discrete periods or use a time interval that conforms to ISO 8601:2004(E). |
| **Examples** | `morning`, `night`, `6:00:00Z/12:30:00Z` (the interval between 6am UTC and 12:30pm UTC) |
| **Controlled vocabulary** | `dawn`; `dusk`; `morning`; `noon`; `afternoon`; `night` (or option of specifying the day time) |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Can we have a term with values like that: discrete periods and time interval?

**Comment by fonturbel** [comment]
I would get rid of the time periods and keep only the six options stated above (dawn; dusk; morning; noon; afternoon; night)

**Comment by zedomel** [comment]
@fonturbel  the problem that I see with discrete periods is that they can be very subjective. What is the definition of `dawn`? If we go to that way, we should define each of the controlled vocabulary terms precisely. For example:

-`dawn`: *the first appearance of light in the sky before sunrise*. It can also be subjective, since the specific time of the sunrise changes during seasons and geographic locations. 

I'm not saying that we can't adopt discrete periods, I'm just warning about the ambiguities that may rise when using it.

**Comment by viniciusduartina** [comment]
I would make both (discrete and continuous values) oppened.

**Comment by pietrokiyoshi** [comment]
I prefer the option to leave both the time interval and discrete periods.

**Comment by joiceiamara** [comment]
This should not be exclusive, since the anthesis may occur at any time of day in some cases. Perhaps include a controled vocabulary.

**Comment by carmensspires** [comment]
I believe that the best way would be to offer numerical options. One way would be to divide the day into 4 periods, with 6 hours each: 1: 00-6: 00AM; 6: 00-12: 00AM; 12: 00-18: 00PM and 18: 00-24: 00PM.

**Comment by arech2003** [comment]
I would go for the discrete intervals dawn; dusk; morning; noon; afternoon; night. We always we loose information when transforming continuous gaps into categories. However opening time is not precise and broad categories as specified seems to deal well with the information demanded. There are definitions for each of these categories but I am not sure we need them, as for this information I will go with something more general.

**Comment by zedomel** [comment]
@carmensspires  this periods that you suggested can be used as definitions of the terms in the controlled vocabulary. For example:

- `morning`: 6:00AM - 12:00AM
- `afternoon`: 12:00AM - 18:00AM

What do you guys think?

It will be better that the term be exclusive discrete or continuous, not both! 
But again, I don't see any problem in maintain the time continuous and let people decide the best time intervals. A example is the term `dwc:eventTime`

- `dwc:eventTime`: `The time or interval during which an Event occurred.` 

With that definition (**time or interval**) people can fill the term with any time or interval, even it is not accurate as @carmensspires  suggested. For example it will be possible to fill the term with values:
- 06:00AM - 12:00AM (not so accurate)
- 12:41PM - 17:55PM (accurate)

@arech2003  regarding to data transformation from continuous to discrete categories, this can be a problem. But, the inverse transformation will be not possible and we will losing information using discrete values. And what about a flower that is open from 06:00AM to 06:00PM? Using discrete periods will require the definition of many categories comprising different combinations of **initial time** and **final time**. By other hand, using continuous time (even not accurate measurements) the person who is working with the data would create his/her own discretization rules:

- 06:00AM - 06:00PM  can be discretize to  a list: `morning`, `afternoon` or `daylight`

Again, using only continuous values here will make the term more general covering most use cases. It does not mean that **internally** in REBIPP database we can't use discrete periods (`dawn`, `morning`, etc.) we just have to define internally the meaning of this controlled vocab. Then, when sharing data with others players (e.g GBIF), the data will be pulled out from the database and standardised following the internal rules:
- `morning`will become `06:00AM - 12:00AM`

**Comment by arech2003** [comment]
Ok, @zedomel I am convinced by your argument!

**Comment by pjbergamo** [comment]
Agree with @carmensspires and the subsequent suggestion of @zedomel

**Comment by cepnunes** [comment]
Nothing to add here!

**Comment by Andre-Luis-Acosta** [comment]
I ask here for colleagues if "explosive anthesis", which would be related with "fowerOpeningType", would not be something to be taken into account? Two examples [example1](https://youtu.be/9Szi0e6Aahk?t=34), [example2](https://youtu.be/rGR146xy0Mk)

**Comment by Mardiore** [comment]
Nothing to add here. It was great after the discussion!

**Comment by paf1306** [comment]
I agree with @zedomel. Nothing else to add.

**Comment by zedomel** [comment]
**New definition**: `The time or interval which chasmogamous flower opens exposing its reproductive parts` (simplified)
