### ISSUE TITLE
caste

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#5]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:AnimalTrait |
| **Label** | caste |
| **Definition** | The society division that is specialized in the function it performs and distinguished by anatomical or morphological differences from other individuals of the society |
| **Comments** | Best pratices is to use a controlled vocabulary |
| **Examples** | `soldier`, `queen `, `worker ` |
| **Controlled vocabulary** | `soldier`, `queen `, `worker ` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Term definition:
`The society division that is specialized in the function it performs and distinguished by anatomical or morphological differences from other group of individuals in the society`

@pzermoglio: 
> not sure how this would apply to eg event

> what distinguishes these two? `Anatomical or morphological`

Actually, it would apply to the Occurrence or Taxon.

It will linked to the core `dwc:Event` but using EMoF we can linked to a `dwc:Occurrence` using the term `dwc:occurrenceID` in the EMoF extension. Can we do it?

**Comment by fonturbel** [comment]
If we have this term, we should have another term for sociality (solitary, social primitive, eusocial)

**Comment by zedomel** [comment]
@fonturbel  this is only `Animal` descriptor we are proposing. Darwin Core has some terms that can be useful for animals like `sex` and `lifeStage`. 
I think we need consulting more people to contribute on animal terms. Common measurements in interaction studies are **body size**, **body length**, **body weight**, **intertegular distance**. 

Your comment is very pertinent, since we need more terms to characterize the **animals**.

But, we can let it for next round (next version).
