### ISSUE TITLE
flowerType

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#50]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | flowerType |
| **Definition** | The type of flower describing whether the flower's corolla opens or not, exposing its reproductive parts to floral visitors (cleistogamous, chasmogamous or mixed). |
| **Comments** | Recommended best practice is to use a controlled vocabulary. Example: Plant Trait Ontology |
| **Examples** | `cleistogamous`, `chasmogamous`, [`http://purl.obolibrary.org/obo/TO_0000882`](http://purl.obolibrary.org/obo/TO_0000882) |
| **Controlled vocabulary** | [Plant Trait Ontology](http://purl.obolibrary.org/obo/TO_0000881) |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Change term definition to: 
`The type of flower describing whether the flower's corolla opens or not, exposing its reproductive parts to floral visitors.`

**Comment by fonturbel** [comment]
I am confused by the controlled vocabulary options...

**Comment by zedomel** [comment]
@fonturbel could you share your thoughts with us? What is confused? The ontology term: [http://purl.obolibrary.org/obo/TO_0000882](http://purl.obolibrary.org/obo/TO_0000882) ?

**Comment by viniciusduartina** [comment]
Agree with definiton and vocabulary. Please, include mixed as an option in the controled vocabulary.

**Comment by pietrokiyoshi** [comment]
Ok with me regarding the terms.

**Comment by joiceiamara** [comment]
Nothing to add

**Comment by carmensspires** [comment]
Nothing to add.

**Comment by arech2003** [comment]
Nothin to add and agree with @zedomel

**Comment by carmensspires** [comment]
Nothing to add

**Comment by cepnunes** [comment]
I believe the name of the trait could be improved here as "flowerType" can be interpreted as other concepts. I suggest changing the name to "flowerOpening" or "flowerOpeningType" to be more specific to the user. Moreover, I agree with adding the "mixed cleistogamous and chasmogamous" option to the controlled vocabulary.

**Comment by Mardiore** [comment]
I agree with @cepnunes "flowerType can be interpreted as other concepts" (e.g. corolla type) and I agree with @viniciusduartina.

**Comment by anselmoeco** [comment]
The point raised by @cepnunes is important to be considered.

**Comment by paf1306** [comment]
Nothing else to add.

**Comment by zedomel** [comment]
**New label**: `flowerOpeningType`
**New definition**: `The type of flower describing whether the flower's corolla opens or not, exposing its reproductive parts`
