### ISSUE TITLE
functionalFlowerLifespan

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#51]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | functionalFlowerLifespan |
| **Definition** | The total period of time in hours in which the female and male flower parts of the recorded plant species are functioning. |
| **Comments** | The period of time when stigma is receptive to the germination of pollen grains, ovules are receptive to the pollen tubes and anthers present viable pollen grains. |
| **Examples** | `1`, `8`, `72`, `120` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
I don't feel qualified to issue an informed opinion about this.

**Comment by zedomel** [comment]
This is related to a species trait or a measurement taken from an individual plant? Same question as in #57 .

**Comment by pietrokiyoshi** [comment]
It is recorded for an individual flower/plant, but sometimes it is extrapolated to the whole species. So, we should specify (?)

**Comment by viniciusduartina** [comment]
Could be numbers with decimals.

**Comment by carmensspires** [comment]
This characteristic is measured at the level of the individual and we can have an average for a population of flowers. The definition is reflecting this. I have nothing to add.

**Comment by arech2003** [comment]
The trait refers to an individual whose anthesis was measured. Maybe number could include decimals, but I don´t know how relevant it will be to add such a detail. By functioning are we referring to the Anthesis time or visitation time? I feel like the word anthesis should appear in the definition if referring to it.

**Comment by zedomel** [comment]
@carmensspires  I don't see how the definition is reflecting the individual x population measurements. As an example imagine that you receive/download a dataset which you don't know nothing about and you come across a `funcionalFlowerLifespan` of `72`. **How could you know that this measurement is about a specific **individual** or the whole **population** of a plant species?** The definition does not say anything about it (it is ambiguous).

@arech2003  and @viniciusduartina  what about change the definition to something like `flowerLongevity`(#48) requiring a **time interval** instead a number of hours? This **time interval** must not be accurate, we can just use intervals like: `06:00AM - 11:00AM`. 

Should we change the **label** to `functionalFlowerLongevity` or `functionalFlowerPeriod`? If we go for **time interval** maybe it can be labelled as `functionalFlowerTime`.

Just some ideias.

**Comment by viniciusduartina** [comment]
@zedomel I see no problem in using time interval or the number of hours as integer if it is not possible to add decimals.

**Comment by cepnunes** [comment]
Ideally it would be nice to have both options, the total of hours and start time and end time, of male and female lifespan separately. However, I imagine adding more and more fields and options is not the goal here, so I would stick to the way it is now.

**Comment by zedomel** [comment]
@cepnunes  do you have examples of datasets doing this distinction (male/female)? 
Maybe, it is possible to separate them using this term in conjunction with `flowerSex`(#20 ), but I need to see examples of data.

**Comment by cepnunes** [comment]
@zedomel it would be neat to use this functionalFlowerLifespan in conjunction with flowerSex (#20)  ONLY IN THE CASES in which the flowers are SOLELY FEMALES or SOLELY MALES. In hermaphrodite flowers, it would become messy with the need of separation of the male and female functions. It's something to think about.

**Comment by pjbergamo** [comment]
I am not seeing how this term and flowerSex go together.
What I understood is that @cepnunes mentioned cases of dichogamy, i.e., when the same flower is first male (of female) and sometime after the opposite sex function starts. Therefore, separate time spans for male function and female function works only for hermaphrodite flowers actually.
I would say that this is adding to much complexity, as it would require to specify the gender function operating in each amount of time.

**Comment by cepnunes** [comment]
@pjbergamo and @zedomel, Sorry if I wasn't clear. I meant that the use of functionalFlowerLifespan in conjunction with flowerSexuality (#20) would only work for flowers that bear a single sex function, for instance, when a flower is always male and only male. In other cases, I agree with @pjbergamo  in that it could make the form much more complex.

**Comment by Mardiore** [comment]
In my opinion the definition is good and understandable. I agree with @viniciusduartina, and I suggest the maintenance of he term functionalFlowerLifespan, because it is usual in the literature.

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
**New definition**: `The total period of time in hours in which the female and male flower parts a plant species are functioning.`
We will maintain the unit of time in hours for simplicity.
