### ISSUE TITLE
habit

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#52]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | habit |
| **Definition** | The general appearance, characteristic form, or mode of growth of a plant species represente in the record. Also refer to the substrate where the plant grows by which the aerial parts are supported. |
| **Comments** | The most usual terms are tree, bush, climber, herb. Additionally, the mode of growth (aquatic, terrestrial, rupiculous, epiphytic) can be included here. Examples: aquatic herb, epiphytic herb, rupiculous bush. Term reference (literature): Gonçalves and Lorenzi (2011). |
| **Examples** |  |
| **Controlled vocabulary** | tree; bush; climber; herb; epiphytic herb; aquatic herb; rupiculous herb; terrestrial tree; terrestrial bush; terrestrial climber; terrestrial herb; rupiculous tree; rupiculous bush; rupiculous climber; rupiculous herb |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Can we simplify the controlled vocabulary? Is it mixing different concepts: **habit** x **substrate of growth** x **terrestrial** x **aquatic**?

Can we use this vocabulary: [Flora Phenotype Ontology](http://aber-owl.net/ontology/FLOPO/#/!http://purl.obolibrary.org/obo/FLOPO_0900032)?

**Comment by fonturbel** [comment]
Too many controlled-vocabulary categories, I suggest to simplify it: tree, bush, herb, climber

**Comment by zedomel** [comment]
@fonturbel  following my previous comment, The [Flora Phenotype Ontology](http://aber-owl.net/ontology/FLOPO/#/Browse/%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFLOPO_0900032%3E) defines the following terms for `whole plat growth form`:

- `whole plant arborescent` (synonym: tree)
- `whole plant frutescent` (synonym: bush, shurb)
- `whole plant herbaceous`:
    - `whole plant forbacious` (synonym: forb)
    - `whole plant graminoid` (synonym: grass-like)
- `whole plant lianescent` (synonym: liana, climber)

These terms make sense?

Additionally the Flora Phenotype Ontology defines other terms in the `whole plant lifeform` like the term `whole plant epiphytic`, so I suspect that the original controlled vocab proposed for this term is mixing different concepts: **growth form** and **life form**.

**Comment by pietrokiyoshi** [comment]
To me it seems that  Flora Phenotype Ontology  is a good standard.

**Comment by viniciusduartina** [comment]
Agree! Please, correct "represente" to "represented".

**Comment by carmensspires** [comment]
I suggest keeping only the first sentence in the definition:" The general appearance, characteristic form, or mode of growth of a plant species represente in the record."

**Comment by arech2003** [comment]
I agree wit @carmensspires. The second part is mixing habit with habitat... And this should be two collumns.

**Comment by zedomel** [comment]
@carmensspires  I agree to. 

So, can we just keep the controlled vocab as defined in FLOPO  for `whole plat growth form`?

**Comment by joiceiamara** [comment]
I agree with @carmensspires and in using FLOPO

**Comment by Mardiore** [comment]
I agree with @carmensspires and @arech2003., but I suggest only "tree, bush, herb, climber".

**Comment by anselmoeco** [comment]
I agree with @carmensspires and @Mardiore !

**Comment by paf1306** [comment]
I agree with @carmensspires to use 2 columns for plant habit and habitat. Nothing else to add.

**Comment by zedomel** [comment]
**New definition**: `The general appearance, characteristic form, or mode of growth of a plant species`
