### ISSUE TITLE
humanUse

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#53]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | humanUse |
| **Definition** | Use made of the plant species by humans. Ways in which species are utilized by people, including Folklore |
| **Comments** | Recommended best practice is to use a controlled vocabulary. Example: Economic Botany Data Standard (http://www.kew.org/tdwguses/index.htm) |
| **Examples** | `human food `, `animal food`, `medicine`, `ritual` |
| **Controlled vocabulary** | human food; animal food; medicine; ritual; enteogenous; ornamental (gardening and landscaping); raw material; energy (timber, biofuel); green manure; other (specify). |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
I am not sure how relevant is this information for the database given its purpose. Maybe we can get rid of it?

**Comment by zedomel** [comment]
@fonturbel  your assertion is very relevant when we think about the purpose of the data standard in the context to the database. 

But we should think about them **separately**, one thing is the data standard which anyone (including people outside REBIPP and its database) can use to develop their own solution, and other thing is our database. 

When implementing our database we can get rid of it, even the term is defined in the data standard. The database does not have to include all terms in the standard, and also, the data standard does not have to include all term in the database. **They are different things**.

Making an analogy to natural languages, the data standard act as international or a common language which system use to communicate with each other. Your database can be a **Portuguese** "native speaker", but in order to communicate with a **Spanish** "native speaker" it must use a **common language** (e.g. **english** = the data standard). Sometimes, we find words in Portuguese or Spanish that do not have translation to English, on other hand, we also find words in English that do not have translation to Portuguese and Spanish, but we can still communicate each other, although the understanding will be compromised.

**Comment by viniciusduartina** [comment]
Ok with me!

**Comment by pietrokiyoshi** [comment]
Ok

**Comment by joiceiamara** [comment]
nothing to add

**Comment by carmensspires** [comment]
This information is very important considering the work on pollination carried out in agricultural environments with cultivated plants or wild species with potential for use.

**Comment by arech2003** [comment]
It is fine for me.

**Comment by cepnunes** [comment]
Nothing to add.

**Comment by Andre-Luis-Acosta** [comment]
I suppose that the cosmetic use (ex: beeswax) fits in medicine .. so ok here.

**Comment by Mardiore** [comment]
Ok for me

**Comment by paf1306** [comment]
Nothing to add.

**Comment by zedomel** [comment]
Not changed
