### ISSUE TITLE
matingSystem

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#54]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | matingSystem |
| **Definition** | The general mode of gene transfer from one generation to the next through sexual reproduction of the plant species represented in the `Occurrence`. |
| **Comments** | Recommended best practice is to use a controlled vocabulary. |
| **Examples** | `autogamous`, `xenogamous` |
| **Controlled vocabulary** | `autogamous`; `xenogamous` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
OK with me, nothing to add.

**Comment by zedomel** [comment]
This a term related to the plant species, should we do the same as in #57 (use `dwc:Taxon`as core and `dwc:Occurrence` as extension) or it is fine to use with `dwc:Occurrence` as core?

Should we extended the controlled vocab with the term `geitonogamy` ?

**Comment by viniciusduartina** [comment]
I think you should include geitonogamy as an option, but these values should not be exclusive because the same plant could reproduce by autogamy and xenogamy, for example.

**Comment by pietrokiyoshi** [comment]
@viniciusduartina agree!

**Comment by zedomel** [comment]
@viniciusduartina  so we should allow a list of values. 
**New definition**:  `A list (concatenated and separated) of the general modes of gene transfer from one generation to the next through sexual reproduction of the plant species represented in the Occurrence.`
Add to **Comments**:  `Recommended best practice is to separate the values in a list with space vertical bar space ( | )`

Is it better?

**Comment by arech2003** [comment]
Why not only The general modes of gene transfer from on generation to the next through sexual reproduction othe the plant species represented in the occurrence? To me general modes is already in the plural and can include both if required. Using "a list" it suggest to me that one should find more than one always... Geitonogamy is a mix between mating system and pollination system as it still autogamous from the genetic perspective (maybe not if we go very deep as plants have modules in different branches, but nobody will have data for this) but it is not able to set fruit without pollination moving pollen from flower to flower within the individual. At the end of the day I feel we do not loose any information adding it despite its complexity...

**Comment by joiceiamara** [comment]
If using "a list" suggests that one should use more than one, other cases should be review, for instance case #43... however, I do not think that this is the case. @zedomel suggestion works fine to me. Perhaps set the example, as was done for the case I mentioned.

**Comment by zedomel** [comment]
@arech2003 and @joiceiamara  I understand the problem with the `a list...`, but I feel that we should make explicit that the term accepts multiple values and it must be **concatenated and separated**. We can remove it from the definition and use the plural **general mode(s)** as @arech2003  suggested. But we should include the sentence `a list...` into the **Comments**.

**Comment by joiceiamara** [comment]
@zedomel, actually I have no problems using "a list" and so as not to appear that more than one entry should be used, we could use the example as **"autogamous, xenogamous, autogamous | xenogamous"**

**Comment by carmensspires** [comment]
Nothing to add

**Comment by viniciusduartina** [comment]
@zedomel, it seems that a list will do the job. Another observation: mating may occur not only "through sexual reproduction". Moreover, mating is a not a species trait. Thus I would reconsider (if possible) the definition as "A list (concatenated and separated) of the general modes of gene transfer from one generation to the next through reproduction."

**Comment by zedomel** [comment]
@viniciusduartina  the definition comes from Carsodo et al. 2018:
> The different terminologies within the mating systems consider the mode of gene transfer from one generation to the next through **sexual** reproduction.

But, of course, we can create our own definition as you suggested. Could you give examples and controlled vocab terms for that?

**Comment by cepnunes** [comment]
Agree with @viniciusduartina . Nothing to add!

**Comment by viniciusduartina** [comment]
@zedomel, I think we can skip the "sexual" word from the definition of Cardoso et al. 2018 with no prejudice because it is a little bit misleading. I would suggest the vocabs: autogamous, xenogamous and geitonogamous. Again, such values may be not exclusive.

**Comment by zedomel** [comment]
@viniciusduartina this term refers to the individual or to the species? Depends on that, should this term still accept multiple values?

**Comment by Mardiore** [comment]
Agree with @viniciusduartina . Nothing to add!

**Comment by paf1306** [comment]
I also agree with @viniciusduartina . Nothing else to add.

**Comment by zedomel** [comment]
**New definition**: `A list (concatenated and separated) of the general modes of gene transfer from one generation to the next through reproduction of a plant species`
**Comments**: `Recommended best practice is to separate the values in a list with space vertical bar space ( | )`
