### ISSUE TITLE
ovuleQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#55]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | ovuleQuantity |
| **Definition** | A number or enumeration value for the quantity of ovules in flower(s) of the represented plant species. |
| **Comments** |  |
| **Examples** | `3`, `4`, `7.45` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Maybe we can remove `or enumeration value` from the definition once it is a numeric measurement.
Also, we can simplify the definition to do not mention the `represented plant` once it will be implicit by the relationship of this term with the **plant** `dwc:Occurrence`.

New definition (proposal): `The quantity of ovules in the flower(s) of a plant species`.

The number of ovules is almost homogeneous within plant species and it is used in taxonomy for classification. But there is a confusion here if the term is related to a measure taken from a specific **flower** of a **plant individual** or it is a *property* of a **plant species** taken from literature.

The actual definition made no assumption about these differences, and I think it should not do any assumption. But can we still use **`ovules in flower(s)`** (singular and plural)? Singular means a measure taken from a **particular flower of a particular plant individual** (a measurement)? And the plural means what? A average? A species trait? 

Putting it in other terms I see two different ways to define this term:
`The quantity of ovules `**`expected`**` to be found in the `**`flowers`**` of a plant species`
Or
`The quantity of ovules `**`found`**` in `**`a flower`**` of an individual plant`

Can we include both scenarios? How?

**Comment by fonturbel** [comment]
In my opinion the second definition (The quantity of ovules found in a flower of an individual plant) is correct, and I'll keep it as a numeric field, this info is important for fruit set and seed set estimations.

**Comment by zedomel** [comment]
@fonturbel  if we adopt this definition `The quantity of ovules found in a flower of an individual plant` then we are expecting people to take measurements of the quantity of ovules in a **specific** flower of an individual. It is fine if this measurement is related to the recorded plant `Occurrence`, but I'm no sure if it makes sense when we get this value (**quantity of ovules**) from literature and linked it to the `Occurrence`. Because, following the definition, someone who receive the data will interpreted it as measurement of the individual and not a measurement or fact of the plant species. 

Let's see, what others think about it.

**Comment by viniciusduartina** [comment]
The definition "The quantity of ovules foundina flower of an individual plant" seems to be bette because we always count the number of ovules in specific flowers. However, the mean number of ovules can be used as a value for a population or even an species. Some species has a very conservative number of ovules per flowers (e.g. Rubiaceae), but others has highly variable number of ovules per flower (e.g. Melastomataceae).

**Comment by pietrokiyoshi** [comment]
Agree with @viniciusduartina

**Comment by zedomel** [comment]
@viniciusduartina so we should allow mean values or not? 
The definition `The quantity of ovules found in A flower of AN individual plant` makes explicit that it is an absolute value, and can't be interpreted as mean value for a population or a species. 

Imagine if someone gives you a dataset with that information, how could you know if this value is about a specific flower, a population or a species?

**Comment by CADDE-CENTRE** [comment]
It would need prior specification if the OvuleQuantity is variable or fixed per species, and then the average amount is posted here when it is variable or the absolute amount when fixed. Zedomel, could creating new accessory fields be a possibility?

**Comment by Andre-Luis-Acosta** [comment]
It would need prior specification if the OvuleQuantity is variable or fixed per species, and then the average amount is posted here when it is variable or the absolute amount when fixed. Zedomel, could creating new accessory fields (eg. ovuleAmount = variable/fixed) be a possibility?

**Comment by zedomel** [comment]
@Andre-Luis-Acosta I'm not sure if we should go that way.  At this time we should avoid as much as possible adding new terms and keep the standard as simpler we can. Adding some dependent terms will make the usage of the standard more complex, and people could get confused and use those terms incorrectly. Imagine a scenario where a person fill the term `ovuleQuantity` but do not provide any value for `ovuleAmount`. From the perspective of the standard it will be incorrect, but still acceptable (the standard is just a guide for people share data, it does not check how it is used). 

Of course, a data quality analysis later can identify such incoherences, but it will dependent of the data quality methods applied by each data publisher/aggregator.

I confess that mixing individuals attributes with species and population attributes is very confused to me. Darwin Core is based on `Occurrence` of organisms, despite it can be used to share species attributes.   

Maybe @pzermoglio and @tucotuco can help us here :-D. The same problem happens to other terms (species/average x individuals/absolute measurements or facts).

**Comment by arech2003** [comment]
To me: The quantity of ovules found in a flower of an individual plant is a good definition and require people to count ovules in the ovaries to fill the dataset. General numbers from literature cannot be used for this purpose, since even when very conserved one can find variation among populations for some species.

**Comment by joiceiamara** [comment]
I agree with @arech2003

**Comment by carmensspires** [comment]
I also agree with @arech2003.

**Comment by viniciusduartina** [comment]
I agree with @arech2003 that we should keep number of ovules per flower.

**Comment by zedomel** [comment]
Very good folks! Thanks!

So, following what @arech2003  says we should have something like:

| occurrenceID | measurementID | measurementType | measurementValue |
|-----:|-----:|-----:|-----:|
| 1 | 1 | `ovuleQuantity` | 6 | 
| 1 | 2 | `ovuleQuantity` | 5 | 
| 2|  3 | `ovuleQuantity` | 6 | 

Where `measurementID` are measurements for the flowers `1` to `3` linked to **individuals** (`occurrenceID`). In other words, we have measurements of `ovuleQuantity` for **two** flowers (`1`  and `2`) of the **occurrence** `1` and one measurement for one flower (`3`) of the **occurrence** `2`. Is it right?

**Comment by cepnunes** [comment]
It isn't clear to me whether it would be possible to insert more than one interaction linked to the same plant individual and how it is going to work. However I believe it would be nice to have a way to include summarized data for this, such mean and standard deviation at least. That would allow to include some data from literature that is not individualized by flower. The same concern applies for other traits of individual flowers.

**Comment by zedomel** [comment]
@cepnunes  I'm studying a way to do that without messing up the interpretation of the terms. Maybe, we will have to use separated terms for specify if a measurement if an individual measurement or an aggregate measurement (e.g. average).
I will back with more information.

**Comment by MMM-2021** [comment]
> The definition "The quantity of ovules foundina flower of an individual plant" seems to be bette because we always count the number of ovules in specific flowers. However, the mean number of ovules can be used as a value for a population or even an species. Some species has a very conservative number of ovules per flowers (e.g. Rubiaceae), but others has highly variable number of ovules per flower (e.g. Melastomataceae).

I agree with Vinicius too

**Comment by MMM-2021** [comment]
> To me: The quantity of ovules found in a flower of an individual plant is a good definition and require people to count ovules in the ovaries to fill the dataset. General numbers from literature cannot be used for this purpose, since even when very conserved one can find variation among populations for some species.

Correct!

**Comment by paf1306** [comment]
@zedomel I think that is a good way to include this measure. 
 "...Where `measurementID` are measurements for the flowers `1` to `3` linked to **individuals** (`occurrenceID`)..."
Values from average and standard deviation could be calculated from this list of data.  I also agree with @viniciusduartina and @arech2003. Nothing else to add.

**Comment by zedomel** [comment]
**New definition**: `The quantity of ovules of a particular flower of an individual plant`
