### ISSUE TITLE
selfIncompatibilityType

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#56]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | selfIncompatibilityType |
| **Definition** | The type or class of the self-incompatibility system of the plant species. |
| **Comments** | If a self-incompatibility system is absent this term should be filled according (`absent`). Recommended best practice is to use a controlled vocabulary. |
| **Examples** | `gametophytic`, `sporophytic`, `absent`,`unknown` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by fonturbel** [comment]
Why not making it more simple: self-compatible or self-incompatible (two categories of controlled vocabulary)

**Comment by zedomel** [comment]
The same question of #57.

@fonturbel the controlled vocabulary is a recommendation. So, people are free to adopt any vocabulary of terms that they like. We can define a controlled vocab and recommend it adoption, this vocab can have more specific terms like `gametophytic` and also more general terms like `self-compatible`, then  people can choose each term to use.

So my suggestion of the controlled vocab is based on [Cardoso et al. 2018](https://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-33062018000300329):
- `gametophytic`
- `sporophytic homomorphic`
- `sporophytic heteromorphic`
- `sporophytic`
- `late-acting`
- `self-compatible`
- `self-incompatible`
- `absent`
- `unknown`

This vocab covers most of the use cases?

**Comment by pietrokiyoshi** [comment]
Cardoso et al. 2018 is a good and very complete reference. Some researchers may have more detailed information, so a more complete list could be useful. But, not sure what "absent" would mean (absence of self-incompatibility would be self-compatibility).

**Comment by viniciusduartina** [comment]
Agree with @pietrokiyoshi! There is no "absent" selfIncompatibility system.

**Comment by zedomel** [comment]
@pietrokiyoshi and @viniciusduartina  I think that `absent` was proposed as a replacement for `empty` (when the person do not fill that field). But I agree, we can just let the field empty!

**Comment by joiceiamara** [comment]
If the person do not fill the field, can it be considered as "unknow"? Or "unknow" is only to species with no record on the self-incompatibility?

**Comment by zedomel** [comment]
@joiceiamara  I don't see any difference between filling it with `unknown` and let it empty. For me the term `unknown` can be removed from the controlled vocab.

**Comment by arech2003** [comment]
Nothing to add beyond the already mentioned.

**Comment by carmensspires** [comment]
Nothing to add

**Comment by cepnunes** [comment]
Nothing to add as  well!

**Comment by paf1306** [comment]
I agree with @zedomel to let it more simple if we choose to use a controlled vocabulary. Nothing else to add.

**Comment by zedomel** [comment]
Not changed
