### ISSUE TITLE
sexualSystem

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#57]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:PlantTrait |
| **Label** | sexualSystem |
| **Definition** | The gender expression and its occurrence at population or species levels. It is based in the presence and distribution of fertile whorls within the flower. |
| **Comments** | Recommended best practice is to use a controlled vocabulary. |
| **Examples** | `monoceius`, `dioceius` |
| **Controlled vocabulary** | `monoecious`; `ginomonoecious`; `andromonoecious`; `trimonoecious`; `dioecious`; `temporal dioecious` (monoecious + dichogamy); `ginodioecious`; `androdioecious`; `tridioecious`; `poligamodioecious` |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
I will blah blah blah

**Comment by FWAmorim** [comment]
testing...

**Comment by kaynaagostini** [comment]
Teste

**Comment by Favosgyrl** [comment]
Testandooooo

**Comment by fonturbel** [comment]
Nothing to add, it seems fine

**Comment by zedomel** [comment]
@pzermoglio can we use this term with `dwc:Occurrence`? The definition is based on plant species or population, and not related to the organism in the `dwc:Occurrence`. The concept is fine, since the sexual system is a property of a plant population or species. 

Usually, we will have repeated values of this term to all `Occurrence`s of same species in a dataset. Examples:

| occurrenceID | scientifcName | sexualSystem | decimalLatitude | decimalLongitude |
| ------------- |:-------------:| -----:| ------:| ------:|
| occ 1  | *Ilex aquifolium* | dioecious  | -45.2548 | 23.5846 |
| occ 2 | *Ilex aquifolium*  |  dioecious | -44.2568 | 22.3565 |
| occ 3 | *Alnus serrulata* | monoecious | -41.26485 | 23.4846 |

Maybe this term should be used with `dwc:Taxon` class as core, and `dwc:Occurrence` as extension. What do you think?

**Core**:
| taxonID | scientifcName | sexualSystem |
| ------------- |:-------------:| -----:|
| tax 1|  *Ilex aquifolium* | dioecious |
| tax 2 | *Alnus serrulata* | monoecious |

**Occurrence extension**:
| coreID | occurrenceID | decimalLatitude | decimalLongitude |
| ------------- |:-------------:| -----:| ------:|
| tax 1 | occ 1  | -45.2548 | 23.5846 |
| tax 1 | occ 2 |  -44.2568 | 22.3565 |
| tax 2 | occ 3 | -41.26485 | 23.4846 |

**Comment by viniciusduartina** [comment]
Please add "Cosexuality" as a value in the controled vocabulary following Cardoso et al. 2018. This reference should be available for further reference. https://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-33062018000300329&lng=en&tlng=en

I think it is fine to use this term with dwc:Occurrence and dwc:Taxon. However, different populations of the same plant species can have different sexual systems. Is it a problem?

**Comment by zedomel** [comment]
@viniciusduartina  thank for your contribution to the controlled vocab. 

Regards your question: how are populations defined? Spatially? Genetically? The issue that I see here is that we don't have means to know from which population the plant individual in the `dwc:Occurrence` belongs (we don't have a term for that). So, in the end, following the definition of this term someone who get the data will interpret it as **the individual in this `dwc:Occurrence` belongs to some unknown (not specified) population which shows  the given `sexualSystem` (e.g. `cosexuality`, `,monoecius`) OR that all individuals of the species shows the given `sexualSystem`.**

My suggestion, in order to remove such ambiguity, is to change the definition so the term refers only to the population: `The gender expression in the population which the individual(s) in this Occurrence belongs to. It is based in the presence and distribution of fertile whorls within the flower.` **We can improve it!** But the idea is to change the definition to be clear that this term is an attribute of the **population** instead of the **individual** itself. Makes sense?

**Comment by joiceiamara** [comment]
As @viniciusduartina pointed out, different population of plant species can have different sexual systems. So sexual system is indeed a species property?  So, I believe that definition proposed by @zedomel seems more appropriated.

**Comment by arech2003** [comment]
Hi, for individual you will always have something to insert in the bataset, for population it is not the case. If one find one individual the entire population could be impossible to reach, in that case to fill the dataset he/she will need to extrapolate the result for the entire population that could be different from the individual recorded. Could that be a problem? Most studies are a collection of single individuals from different species. For the individual the sex is reasonably fix, but for the population it may vary from individual to individual, how to fill a line in the dataset considering interindividual variation?

**Comment by carmensspires** [comment]
I'm getting confused .... Is the definition for the population or for the individual? By the second part of the definition (It is based in the presence and distribution of fertile whorls within the flower) we are referring to the individual. According to @arech2003 comments, it is very difficult to extrapolate to the population from the observations of some individuals. So the definition would not be "The gender expression and its occurrence at individual level. It is based on the presence and distribution of fertile whorls within the flower."?

**Comment by zedomel** [comment]
@carmensspires  I agree with you. But is it possible to know the **sexual system** without observing the population? How could someone know the **sexual system** looking just to one plant individual?

For the individual level the term `flowerSexuality` (#20) should cover that use case?

**Definitions:**
 - **Sexual System** ([Cardoso et al., 2018](http://dx.doi.org/10.1590/0102-33062018abb0124)): `Sexual systems include gender expression and its occurrence at different levels, such as intrafloral, individual, population, or species levels.` 
 
But they also states that <pre>Further classifications are based on the distribution of these floral types within and among the <b>individuals of a given population</b>.</pre>. so a **inter-individual variation**

*Further classifications* includes (but not limited to):
- **Monoecy**: `sexual system in which a` **`population`** `present only unisexual (diclinous) flowers and both staminate and pistillate flowers occur in the same individual``

Perhaps, we need to clarify the concept here before define the term. **What we mean by sexual system**? **How can we measure it**?

**Comment by cepnunes** [comment]
Just a little thing about this descriptor: the spelling of the examples is not correct and is not matching the spelling of the controlled vocabulary. They should be "monoecious" and "dioecious" instead of "monoecius" and "dioecius".

**Comment by viniciusduartina** [comment]
Hi guys! 

I ackonwledge that sexual expression in plants is really messy because it can be defined at the flower level (staminate, pistilate or bisexual), at the indiviual level (male, female ou hemarphrodite) or population level (cosexual, dioceous, monoecious, etc). Therefore, we need a common ground  and I would strongly suggest the use of Cardoso et al. 2018 for reference in this matter. Accordingly to them (and refs within) sexual system is a property of populations rather than individuals. Of course we use the individuals to access traits at population level and it is virtually impossible to acess all the individuas of a population, but I think it is not a problem at all. We do it all the time. I would not recommend to think sexuality as a species trait despite some people do.

I agree with @zedomel that we should leave it as only a population term.

**Comment by Filipi-Soares** [comment]
Hey @zedomel 
I see there are many terms suggested as Controlled vocabulary that can be used to fulfill the sexualSystem metadata field and other metadata elements as well. Some ontologies cover these terms, including the preferred name for the term, stable URLs, and so on. I don't know if it could be useful but maybe you could create a special section in this GitHub repository so we can suggest the definitions for these terms suggested as controlled vocabulary, incorporating ontology definitions when possible. What do you think? For example, in the ECOCORE ontology, they set the term "hermaphroditic" as preferred instead of "monoecious", which is shown as a synonym. In this first moment, I don't think it's necessary to create a very complex structure like an ontology just for these controlled vocabularies you suggest because it could make the standard more difficult to use, but a list of terms with definitions could be helpful.

**Comment by paf1306** [comment]
Hello everyone, I agree with @viniciusduartina, we must use it at a population level in reference to the species.

**Comment by Favosgyrl** [comment]
I also agree!!
Population level must be the best choice.

Att.

Favos
-----------
Profa. Dra. Favízia Freitas de Oliveira
https://orcid.org/0000-0003-4366-5005
*http://lattes.cnpq.br/9780853423702349*
<https://wwws.cnpq.br/cvlattesweb/PKG_MENU.menu?f_cod=5E66D110DC9D1C90BA2337A5AB859A77#>
Coordenação - Laboratório de Bionomia, Biogeografia e Sistemática de
Insetos (BIOSIS)
Curadoria de Invertebrados Terrestres - Museu de História Natural /
Zoologia - MHNBA/MZUFBA
Instituto de Biologia, Universidade Federal da Bahia,
Rua Barão de Jeremoabo, número 668, Campus Universitário de Ondina,
CEP: 40170-115, Salvador - Bahia - Brasil
Fone: (71) 3283-6551, Fax: (71) 3283-6511
WatsApp: (71) 99914-6374
E-mail: favizia.freitas@ufba.br
E-mail alternativo: favosgyrl@gmail.com


Em ter., 2 de mar. de 2021 às 13:23, paf1306 <notifications@github.com>
escreveu:

**Comment by zedomel** [comment]
From Cardoso et al. 2018:
>(1.1) Sexual systems
Sexual systems include gender expression and its occurrence at different levels, such as intrafloral, individual, population, or species levels. It is based in the presence and distribution of fertile whorls within the flower. Flowers may be bisexual, with both stamens (male organs) and pistils (carpels) (female organs), or unisexual, with only male (staminate flower) or female (pistillate or carpellate flower) functional organs (Fig. 2). Further classifications are based on the distribution of these floral types within and among the individuals of a given population.

A new definition is proposed following Cardoso et al. 2018:
**New definition**: `The distribution of floral types within and among the individuals of same population`
**Comments**: `The gender expression is based in the presence and distribution of fertile whorls within the flower (bisexual, staminate flower, pistillate or carpellate flower)`

**Comment by fonturbel** [comment]
I also agree with @viniciusduartina we should keep this descriptor at the population / species level. Therefore, the controlled vocabulary initially proposed should do the trick.

**Comment by Favosgyrl** [comment]
I agree!!!
Excellent...
-----------
Profa. Dra. Favízia Freitas de Oliveira
https://orcid.org/0000-0003-4366-5005
*http://lattes.cnpq.br/9780853423702349*
<https://wwws.cnpq.br/cvlattesweb/PKG_MENU.menu?f_cod=5E66D110DC9D1C90BA2337A5AB859A77#>
Coordenação - Laboratório de Bionomia, Biogeografia e Sistemática de
Insetos (BIOSIS)
Curadoria de Invertebrados Terrestres - Museu de História Natural /
Zoologia - MHNBA/MZUFBA
Instituto de Biologia, Universidade Federal da Bahia,
Rua Barão de Jeremoabo, número 668, Campus Universitário de Ondina,
CEP: 40170-115, Salvador - Bahia - Brasil
Fone: (71) 3283-6551, Fax: (71) 3283-6511
WatsApp: (71) 99914-6374
E-mail: ***@***.***
E-mail alternativo: ***@***.***


Em qui., 11 de mar. de 2021 às 16:47, Francisco E. Fonturbel <
***@***.***> escreveu:

**Comment by pietrokiyoshi** [comment]
I agree with the new definition following Cardoso et al. 2018, as propsed by @zedomel and to keep it at population level as suggested by @viniciusduartina

**Comment by pjbergamo** [comment]
I also agree with following Cardoso et al. 2018 and keeping it at population level. As @fonturbel said, we were already at population level in the controlled vocab.

**Comment by zedomel** [comment]
Thank very much. Closing this issue now!
