### ISSUE TITLE
standingCropFlowerLongevityProperty

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#6]
Term definition:
`The elapsed time in hours or an enumerated value between the moment in which a flower opens and its senescence, describing when the standing crop measures were taken during the flower longevity`

@pzermoglio:
> this is confusing with the first part of the definition. Is it the lifespan of the flower (eg "The elapsed time in hours between the moment in which a flower opens and its senescence") or is it when it was measured? There are two completely different concepts here, longevity and time of measurement

**Comment by fonturbel** [comment]
Repeated?

**Comment by zedomel** [comment]
Removed
