### ISSUE TITLE
styleLength

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#7]
Term definition:

`The average length, from the base to the tip, of the style(s) of the flower(s) of the plant for which the ‘Interaction’ was recordedof this plant Occurrence`

@pzermoglio:
> of all styles of all flowers of the plant?

**Comment by zedomel** [comment]
Particularly I don't like it be the average length (not raw data). 

In practice, the styles are measured for a subsample of the flowers in plant. It is also possible to measure the style length without recording an interaction in that specific flowers. 

Conceptually, the interaction occurs between individuals plant-animal, but some measures are taken from the flower involved in the interaction and other measures are taken from the a subsamples of flowers not involved in the interaction :-(

What we can do here to simplify it?

**Comment by fonturbel** [comment]
If not using the average, how are you going to put all raw values?
