### ISSUE TITLE
attractiveStructure

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#8]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | attractiveStructure |
| **Definition** | The plant structure which is found to visually attract the visiting animal. |
| **Comments** | Recommended best practice is to separate the values (singular) in a list with space vertical bar space ( | ). Recommended best practice is to use a controlled vocabulary such as Plant Ontology (PO) |
| **Examples** | `bract`, `bract \| petal`, [http://purl.obolibrary.org/obo/PO_0009032](http://purl.obolibrary.org/obo/PO_0009032) |
| **Controlled vocabulary** | [Plant Ontology](http://purl.obolibrary.org/obo/PO_0025395) |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Term definition:

`The plant structure which is found to visually attract the visiting animal`

@pzermoglio:
>this can be subjective. Plus, for insects, it depends on the scale, at larger scales it's probably odors that attract, and not visual cues.

**Comment by fonturbel** [comment]
OK after the last changes

**Comment by zedomel** [comment]
Based on the discussion on  #42 , I would define this term as `The flower's structure which visually attracts the visiting animal.`
Also, change the term's label to make explicit that this terms related only to **visual** attractants:

**New label**: `visuallyAttractiveStructure`

Not sure if it should be a `Plant` descriptor or a `Interaction` descriptor (same for #29 ).
