### ISSUE TITLE
collectingBodyPart

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#9]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:Interaction |
| **Label** | collectingBodyPart |
| **Definition** | The animal body part (e.g. organ) used to access the floral resources. |
| **Comments** |  |
| **Examples** | `glossa`, `bill`, `tongue`, [`http://purl.obolibrary.org/obo/HAO_0000376`](http://purl.obolibrary.org/obo/HAO_0000376) |
| **Controlled vocabulary** | [Hymenoptera Anatomy Ontology Portal](http://api.hymao.org/projects/32/public/ontology/) |
| **Darwin Core Class** | Event |
| **Cardinality** | One to one |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
`collectingBodyPart ` term definition:

`The animal body part used to access the floral resources`

`collectingBodyPartLength` definition:

`The length in millimeters of the body part used to access the floral resource`

@pzermoglio:
>not sure `used to access the floral resources` is specific enough.

**Comment by fonturbel** [comment]
The term name is a little bit confusing

**Comment by zedomel** [comment]
@fonturbel  do you have any suggestion?

**Comment by carmensspires** [comment]
collectingBodyPart by definition refers only to pollen?

**Comment by fonturbel** [comment]
> @fonturbel do you have any suggestion?

Something more general: mouth parts, dorsal area, abdomen, or limbs for example...

**Comment by terezagiannini** [comment]
I agree with the idea "Something more general: mouth parts, dorsal area, abdomen, or limbs for example.."
I think there will be little information to inform this field in millimeters

**Comment by pietrokiyoshi** [comment]
I agree with @fonturbel to add something more general. If we consider other resources than nectar (pollen, oil) collection is done with the limbs (mostly) and not mouth parts, for example.

**Comment by RafaelCBorges** [comment]
After thinking for some time on the usability of this term, I could not find a good example of the interest in the length of pollen collecting body part structures. 
In the case of bees it would be mouth parts and legs, but our interest for this field, I believe, sets on the tongue length (which is mostly used for collecting nectar). When thinking of hummingbirds the interest would be on the beak length, which is also the nectar collecting structure. And so on when thinking about bats, butterflies, etc. 
Thus, I suggest changing the name of this term to NectarCollectingBodyPart, which would be more specific in providing the data. 
@fonturbel and @carmensspires, mouth parts, dorsal area, abdomen, or limbs and the structures used to collect pollen are provided in the field animalPlaceOfContact, where a list of all animal body parts in contact to the flower are provided. I think here we can be more specific. 
@terezagiannini, I think millimetres is a good unit for the field NectarCollectingBodyPartLength, as it encompass the smallest (insects), and can be easily converted for inputs from vertebrate taxa (which will be in many many millimetres).  
@pietrokiyoshi, isn't that information already provided in the animalPlaceOfContact field?

**Comment by zedomel** [comment]
Hi people, 

Do I missing something? What is the problem with `collectingBodyPart` label? The definition does not make any assumption about if it is collecting **nectar**, **pollen**, **oil** etc.  Maybe we can expand the definition to accept a list of values:

**Definition**: `A list (concatenated and separated) of animal's body parts used to access the floral resources.`

Then, floral resources here can anything like **nectar**, **oil**, **pollen** and the body parts **legs**, **tongue**, **glossa**, etc.

Does it make sense?

**Comment by zedomel** [comment]
Hi people, 

Since the floral resources can be anything like **nectar**, **oil**, **pollen**, etc. and an animal can collect multiple resources at same time I don't see how this term can be used to capture all this body parts. If we used a *list of body parts* then the term `colectingBodyPartLength` does not make sense, because we can not have a list of **body parts length** due the ordering problem. 

@RafaelCBorges the term `animalPlaceOfContact` can be used to capture structures that the animal is using to collecting pollen, but the term's definition does not explicit says that these body parts are used to collecting. It does say that these body parts **contacts the flower** and just it. If this information if sufficient, then we can go that way.

Following the discussion, my suggestion is to change the term label and definition to:
**Label**: `nectarCollectingBodyPart`
**Definition**: `The animal body part used to collect nectar from the plant nectaries`
**Comments**: `The plant nectaries  can be floral or extrafloral nectaries`

Does it makes sense?

**Comment by RafaelCBorges** [comment]
@zedomel, could the description of animalPlaceOfContact be updated to also include structures used for collecting? Just to include this information.
Anyway, I believe the information about the body parts used for collecting are already included in that definition, as they must be in contact for collecting.
I think the new term label and definition is good.
